select 'exec ' + sys.schemas.name+'.'+sys.objects.name 
FROM    sys.objects A
INNER JOIN sys.schemas ON sys.objects.schema_id = sys.schemas.schema_id
where type = 'P'

SELECT  sys.objects.name, sys.schemas.name AS schema_name


SELECT  'EXEC [' + sys.schemas.name +'.'+ sys.objects.name +']'+CHAR (10) + 'go'
 FROM    sys.objects 
INNER JOIN sys.schemas ON sys.objects.schema_id = sys.schemas.schema_id
WHERE sys.schemas.name != 'SYS'
AND sys.objects.TYPE = 'P'

SELECT  'EXEC [' + sys.objects.name +']'+CHAR (10) + 'go'
 FROM    sys.objects 
INNER JOIN sys.schemas ON sys.objects.schema_id = sys.schemas.schema_id
WHERE sys.schemas.name != 'SYS'
AND sys.objects.TYPE = 'P'




EXEC dbo.periodo_estilo_loja_ii
EXEC dbo.xfkc_fechada_antiga_id_distrito_comercial_mms
EXEC DSS.periodo_estilo_loja_i_ptmp
EXEC dbo.xfk_lk_banco_empresa_custodia_lk_lk_empresa_custodia
EXEC dbo.semana_comercial_item_loja_i_200806_view
EXEC dbo.sp_reestruturacao_dia_secao_200310_u
EXEC dbo.previsao_semana_comercial_sub_depto_loja_II
EXEC dbo.vw_last6quinzenas
EXEC dbo.dia_secao_loja_200712_view
EXEC dbo.xpkc_dia_curva_venda_planejamento
EXEC dbo.price_point2
EXEC dbo.sp_dwh_cobertura_lead_time_i
EXEC dbo.sp_dia_secao_toda_loja_sap_u
EXEC dbo.DF__quinzena__id_sem__7BE6F8DE
EXEC dbo.pedido_bcp
EXEC dbo.similar_item
EXEC dbo.dia_item_loja_ii_final_CTB
EXEC dbo.dia
EXEC dbo.PARA_DELETAR_semana_comercial_item_loja_sap_02_02_2009_bkp
EXEC dbo.xfkc_id_toda_regiao_comercial_mms
EXEC dbo.dia_item_loja_i_200801_new
EXEC dbo.CMP_SAP_corrente
EXEC dbo.XPKmes_tema_loja_iii_new
EXEC dbo.dia_comercial_item_loja_i_DBA
EXEC dbo.xfkc_fechada_antiga_id_regiao_comercial_mms
EXEC dbo.periodo_estilo_loja_i_comercial_200801_view
EXEC dbo.R_alt_201
EXEC dbo.XPKlk_estado_local
EXEC dbo.sp_reestruturacao_dia_secao_200311_u
EXEC dbo.vw_lojas_cds
EXEC dbo.dia_secao_loja_200801_view
EXEC dbo.xpkc_dia_equivalente_ano_anterior
EXEC dbo.PK__price_point2__014ACC79
EXEC dbo.sp_dwh_cobertura_lead_time_s
EXEC dbo.xpkc_dia_secao_toda_loja_sap
EXEC dbo.DF__superviso__id_su__39643D13
EXEC dbo.custo_unitario_medio_item_mms_historico
EXEC dbo.similar_item2
EXEC dbo.dia_sub_classe_loja_200702_view
EXEC dbo.dia_ano_anterior
EXEC dbo.XPKquinzena_secao_loja_2
EXEC dbo.dia_sub_classe_loja_200709_view
EXEC dbo.xpkc_CMP_SAP_Carga_corrente
EXEC dbo.XPKmes_tema_toda_loja_i_new
EXEC RPCUSER.quinzena_item_loja_i_DBA
EXEC dbo.sp_work_marisa_mms_OLD
EXEC dbo.periodo_estilo_toda_loja_i_new
EXEC dbo.xfkc_fechada_antiga_id_toda_regiao_comercial_mms
EXEC dbo.periodo_estilo_loja_i_comercial_200802_view
EXEC dbo.dia_sub_classe_loja_i_ptmp
EXEC dbo.XPKlk_estado_loja
EXEC dbo.sp_reestruturacao_dia_secao_200312_u
EXEC dbo.sp_dwh_previsao_toda_semana_s
EXEC dbo.vw_mes_associacao
EXEC dbo.dia_sub_classe_loja_200712_view
EXEC dbo.XPKdia_feriado_loja
EXEC dbo.FK__price_poi__id_gr__023EF0B2
EXEC DSS.sp_dwh_cotacao_moeda_calc_s
EXEC dbo.dia_todo_prod_toda_loja_i_new
EXEC dbo.DF__superviso__situa__710A430F
EXEC dbo.xpkc_custo_unitario_medio_item_mms_historico_
EXEC dbo.situacao_atraso_ped
EXEC dbo.dia_calendario_comercial
EXEC dbo.PARA_DELETAR_mes_item_loja_sap_02_02_2009_BKP
EXEC dbo.sp_pedidos_d
EXEC dbo.R_alt_83
EXEC dbo.xpkc_CMP_SAP_historico
EXEC dbo.XPKmes_tema_toda_loja_ii
EXEC dbo.sp_work_marisa_MMS_t
EXEC dbo.periodo_estilo_toda_loja_ii
EXEC dbo.periodo_estilo_loja_i_comercial_200803_view
EXEC dbo.R_21
EXEC dbo.XPKlk_estado_transp
EXEC dbo.sp_reestruturacao_dia_secao_200401_u
EXEC dbo.sp_dwh_previsao_semana_s
EXEC dbo.vw_mes_entrega_sol
EXEC dbo.dia_sub_classe_loja_200801_view
EXEC DSS.sp_dwh_cotacao_moeda_d
EXEC dbo.dia_item_loja_i_final_new_stg
EXEC RPCUSER.dia_todo_prod_toda_loja_i_new_teste
EXEC RPCUSER.spBTSInsereDataInventaioSAP
EXEC dbo.situacao_entrega
EXEC DSS.DECOM_estilos_promocao_2007_compras
EXEC dbo.dia_calendario_comercial_ano_anterior
EXEC dbo.sp_atualiza_agregacao_periodo_comercial_u
EXEC dbo.dia_secao_loja_final_new_bcp
EXEC dbo.R_alt_87
EXEC RPCUSER.venda_unitaria_item_loja_wagner
EXEC dbo.XPKmes_tema_toda_loja_iii_new
EXEC dbo.dw_ods_cliente
EXEC dbo.periodo_estilo_loja_i_comercial_200804_view
EXEC dbo.R_22
EXEC dbo.sp_reestruturacao_dia_secao_200402_u
EXEC DSS.sp_audit_carga_rodes
EXEC dbo.vw_periodo_prev_entr
EXEC dbo.vw_grupo_periodo_setor_loja_cobertura_lead_time
EXEC dbo.vw_mes_pl_setor_loja_est
EXEC dbo.dia_secao_loja_200802_view
EXEC DSS.sp_dwh_cotacao_moeda_i
EXEC dbo.pab_ultima_linha
EXEC dbo.dia_todo_prod_toda_loja_ii
EXEC dbo.situacao_estrutura_loja
EXEC dbo.dia_comercial_sub_depto_loja_orcamento
EXEC dbo.sp_dia_todo_prod_loja_sap_u
EXEC DSS.DECOM_estilos_liquidacao_janeiro_2008_compras
EXEC dbo.dia_secao_loja_i_final_bcp
EXEC dbo.R_alt_97
EXEC dbo.alicota_impostos_DW
EXEC dbo.xpkmoeda
EXEC dbo.dw_cac_log
EXEC dbo.vw_loja
EXEC dbo.periodo_estilo_loja_i_comercial_200805_view
EXEC dbo.R_23
EXEC dbo.lk_fornecedor_filial
EXEC DSS.l_processo_furto
EXEC dbo.lk_regiao_comercial
EXEC dbo.vw_dia_comercial_prev_entr
EXEC dbo.sp_check_loja_referencia
EXEC dbo.vw_mes_plfam_loja_forn_ped
EXEC dbo.dia_sub_classe_loja_200802_view
EXEC dbo.setor_precificacao_x_sub_setor
EXEC DSS.sp_dwh_cotacao_moeda_u
EXEC dbo.VW_SRC_CLIENTESCONTATADOS
EXEC dbo.situacao_periodo
EXEC dbo.dia_curva_venda_planejamento
EXEC dbo.PARA_DELETAR_dia_secao_loja_sap_02_02_2009_BKP
EXEC dbo.XPKregiao_comercial
EXEC dbo.R_alt_98
EXEC dbo.xpkc_alicota_impostos_DW
EXEC dbo.PK__motivo_remarca__05A4A1EB
EXEC dbo.sp_work_marisa_t
EXEC dbo.loja_negocio_particionamento
EXEC dbo.periodo_estilo_loja_i_comercial_200806_view
EXEC dbo.XPKlk_fornecedor_filial
EXEC dbo.erro_alicota_ATM
EXEC dbo.sp_reestruturacao_mes_sub_classe_toda_loja_i_new
EXEC DSS.PK__l_processo_furto__05E56464
EXEC dbo.lk_regiao_geogr_cd
EXEC dbo.vw_ano_comercial_prev_entr
EXEC dbo.vw_mes_plfam_loja_tdforn_origem
EXEC dbo.dia_secao_loja_200803_view
EXEC dbo.xpkc_dia_item_loja_i_ptmp
EXEC dbo.xpkc_setor_precificacao_x_sub_setor
EXEC DSS.sp_dwh_curva_semanal_s
EXEC dbo.dia_todo_prod_toda_loja_sap
EXEC dbo.solicitacao
EXEC DSS.DECOM_estilos_promocao_2007_contabilidade
EXEC dbo.dia_equivalente_ano_anterior
EXEC dbo.PARA_DELETAR_dia_todo_prod_loja_sap_02_02_2009_BKP
EXEC dbo.xpkc_regiao_comercial_mms
EXEC dbo.alicota_DW
EXEC DSS.PK__mudanca_negocio__0698C624
EXEC dbo.xpkc_loja_negocio_particinamento
EXEC dbo.periodo_estilo_loja_i_comercial_200807_view
EXEC dbo.R_248
EXEC dbo.R_alt_4
EXEC DSS.lk_classificacao_loja
EXEC dbo.xpkc_faixa_limite_cartao_id_faixa_limite_cartao
EXEC DSS.l_ocorrencia
EXEC dbo.lk_regiao_geogr_fabricante
EXEC dbo.vw_mes_plfam_tdloja_forn_ped
EXEC dbo.dia_sub_classe_loja_200803_view
EXEC dbo.xpkc_dia_item_loja_ii_ptmp_new
EXEC DSS.sp_dwh_curva_semanal_total_s
EXEC dbo.xpkc_dia_todo_prod_toda_loja_sap
EXEC dbo.solicitado
EXEC dbo.pivot
EXEC dbo.dia_feriado_loja
EXEC dbo.sp_estoque_SAP_limpa_datas
EXEC DSS.EM_OWNER
EXEC dbo.periodo_estilo_loja_i_comercial_200808_view
EXEC dbo.R_alt_7
EXEC dbo.PK__lk_faixa_salaria__277140B8
EXEC dbo.sp_reestruturacao_quinzena_secao_200111_u
EXEC DSS.PK__l_ocorrencia__07CDACD6
EXEC dbo.vw_mes_plfam_tdloja_tdforn_origem
EXEC dbo.dia_secao_loja_200804_view
EXEC DSS.sp_dwh_curva_venda_ano_i
EXEC dbo.dias_cobertura_estoques
EXEC dbo.UFNG_ONLY_DIGITS
EXEC dbo.sub_grupo_trib
EXEC dbo.PKC_pivot
EXEC dbo.sp_mes_item_loja_sap
EXEC dbo.XPKregra_icms
EXEC dbo.PK__orcamento__08810E96
EXEC dbo.Faixa_price_point_estoque
EXEC dbo.periodo_estilo_loja_i_comercial_200809_view
EXEC dbo.R_alt_8
EXEC dbo.xpkc_MargemNegativaSAP
EXEC dbo.XPKlk_faixa_ticket
EXEC dbo.sp_reestruturacao_quinzena_secao_200112_u
EXEC dbo.lk_regiao_geogr_local
EXEC dbo.estoque_inicial
EXEC dbo.dia_sub_classe_loja_200608_view
EXEC dbo.vw_mes_prev_entr
EXEC dbo.dia_sub_classe_loja_200804_view
EXEC dbo.sp_dwh_curva_venda_ano_s
EXEC dbo.dias_entrega
EXEC dbo.dia_comercial_item_loja_i_200902_view
EXEC dbo.sub_tipo_solicitacao
EXEC dbo.dia_item_loja_i_comercial_ptmp
EXEC dbo.XPKsaida_cd
EXEC DSS.venda_prevista_semana_ano_anterior
EXEC dbo.SDL_MOVTOA
EXEC dbo.dia_comercial_item_loja_i_200808_view
EXEC dbo.XPKorigem_item
EXEC dbo.Fin_DiaLoja_VW
EXEC dbo.dia_comercial_sub_classe_loja_i_200708_view
EXEC dbo.periodo_estilo_loja_i_comercial_200810_view
EXEC dbo.MargemNegativaSAPTXT
EXEC dbo.XPKlk_forma_pagto
EXEC dbo.sp_reestruturacao_quinzena_secao_200201_u
EXEC DSS.f_ofr_dia_hora_loja
EXEC dbo.lk_regiao_geogr_loja
EXEC dbo.vw_mes_secao_loja_forn_ped
EXEC dbo.PKCDia_Item_loja_venda_new
EXEC DSS.sp_dwh_curva_venda_dia_i
EXEC dbo.dia_sub_classe_loja_200705_view
EXEC dbo.distrito_comercial_mms
EXEC dbo.dia_comercial_item_loja_ii_200902_view
EXEC dbo.supervisor_loja
EXEC dbo.sp_carrega_estoque_SAP
EXEC dbo.XPKsaida_cd_detal
EXEC dbo.R_alt_16
EXEC dbo.SDL_MOVTOD
EXEC dbo.dia_comercial_item_loja_ii_200808_view
EXEC dbo.PK_origem_pedido
EXEC dbo.periodo_item_loja_i_200708_view
EXEC dbo.periodo_estilo_loja_i_comercial_200811_view
EXEC dbo.entrada_cd
EXEC dbo.sp_reestruturacao_quinzena_secao_200202_u
EXEC dbo.negativos_inflados
EXEC dbo.lk_regiao_geogr_transp
EXEC dbo.vw_mes_secao_loja_tdforn_origem
EXEC DSS.sp_dwh_curva_venda_dia_s
EXEC dbo.pab_ultima_linha_dif
EXEC dbo.dia_comercial_sub_classe_loja_i_200902_view
EXEC dbo.supervisor_regional
EXEC dbo.pivot2
EXEC dbo.XPKsecao
EXEC dbo.dia_comercial_item_loja_i_200601_view
EXEC dbo.R_174
EXEC dbo.dia_comercial_sub_classe_loja_i_200808_view
EXEC dbo.XPKC_pedido
EXEC DSS.IS_PROJECT_FACT
EXEC dbo.periodo_estilo_loja_i_comercial_200812_view
EXEC dbo.XPKentrada_cd
EXEC dbo.sp_reestruturacao_quinzena_secao_200203_u
EXEC DSS.l_colaborador
EXEC dbo.lk_secao
EXEC dbo.vw_mes_secao_tdloja_forn_ped
EXEC DSS.sp_dwh_curva_venda_dia_setor_i
EXEC dbo.sp_produtos_inventario_s
EXEC dbo.periodo_item_loja_i_200902_view
EXEC dbo.tabelas_campos
EXEC dbo.PKC_pivot2
EXEC dbo.dia_item_loja_i_ptmp
EXEC dbo.xpkc_secao_loja_corrente
EXEC dbo.periodo_item_loja_i_200601_view
EXEC dbo.SIG_Grupo_Links
EXEC dbo.periodo_item_loja_i_200808_view
EXEC DSS.IS_REP_COL_FACT
EXEC dbo.PARA_DELETAR_sp_vendas_projetadas_u
EXEC dbo.periodo_estilo_loja_i_comercial_200901_view
EXEC dbo.R_176
EXEC dbo.R_26
EXEC dbo.sp_reestruturacao_quinzena_secao_200204_u
EXEC DSS.PK__l_colaborador__0C9261F3
EXEC dbo.lk_semana_ano
EXEC dbo.vw_mes_secao_tdloja_tdforn_origem
EXEC dbo.XPKdia_loja_faixa_ticket
EXEC DSS.SP_DWH_DECOM_DADOS_REAIS_S
EXEC dbo.Fin_DiaLojaPagtoDiacCarta_VW
EXEC dbo.estacao
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200902_view
EXEC RPCUSER.tcarga_dwh_financ
EXEC dbo.dba_cria_custo_venda
EXEC dbo.pivot3
EXEC dbo.dia_comercial_sub_classe_loja_i_200601_view
EXEC dbo.R_alt_29
EXEC dbo.SIG_Grupos
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200808_view
EXEC dbo.xpkc_mes_anterior_calendario_comercial
EXEC DSS.IS_REP_SQL_FACT
EXEC dbo.trimestre_calendario_comercial
EXEC dbo.periodo_estilo_loja_i_comercial_200902_view
EXEC dbo.R_178
EXEC dbo.R_27
EXEC dbo.data_carga_clc
EXEC dbo.XPKlk_gerente_compra
EXEC dbo.sp_reestruturacao_quinzena_secao_200205_u
EXEC DSS.l_coordenador
EXEC dbo.lk_semana_mes
EXEC dbo.vw_mes_sub_classe_loja_forn_ped
EXEC dbo.XPKdia_loja_toda_faixa_ticket
EXEC DSS.SP_DWH_ENVIO_LOJA_S
EXEC dbo.estacao_ano
EXEC dbo.semana_comercial_item_loja_i_200902_view
EXEC dbo.dia_secao_loja_200606_view
EXEC dbo.dba_zera_custo_est
EXEC dbo.PKC_pivot3
EXEC dbo.dia_item_loja_ii_ptmp
EXEC dbo.PK__semana_mes__0E04DDC2
EXEC dbo.R_57
EXEC dbo.SIG_Grupos_Usuarios
EXEC dbo.semana_comercial_item_loja_i_200808_view
EXEC dbo.xpkc_periodo_calendario_comercial
EXEC dbo.IS_REP_STEP_FACT
EXEC dbo.semestre_calendario_comercial
EXEC dbo.periodo_estilo_loja_i_comercial_200903_view
EXEC dbo.R_181
EXEC dbo.R_73
EXEC dbo.PARA_DELETAR_Descontos
EXEC dbo.sp_reestruturacao_quinzena_secao_200206_u
EXEC DSS.PK__l_coordenador__0E7AAA65
EXEC dbo.lk_semestre
EXEC dbo.lkcr2
EXEC dbo.vw_mes_sub_classe_loja_tdforn_origem
EXEC dbo.xpkc_dia_loja_todo_prod_cancelamento_venda_SIV
EXEC DSS.sp_dwh_indice_comercial_s
EXEC dbo.estado_sub_grupo_trib
EXEC dbo.sp_insere_linhas_carga_estoque_dwh_sap_faltantes_i
EXEC dbo.vw_dia_vencimento
EXEC RPCUSER.teste_movto_estoque
EXEC dbo.dt_verstamp003
EXEC dbo.PKC_semana_sub_classe_loja_forn_ped
EXEC dbo.R_182setor
EXEC dbo.SIG_Links
EXEC dbo.CustoUltimaEntradaMMS
EXEC dbo.periodo_estilo_loja_i_comercial_200904_view
EXEC dbo.entrada_cd_detal
EXEC dbo.XPKlk_grupo_centro_responsabilidade
EXEC dbo.sp_reestruturacao_quinzena_secao_200207_u
EXEC dbo.dia_sub_classe_loja_200706_view
EXEC dbo.lk_setor
EXEC dbo.log_pedidos_estoque2
EXEC dbo.vw_mes_sub_classe_tdloja_forn_ped
EXEC dbo.xpk_dia_loja_venda_extranet2
EXEC dbo.sp_dwh_indice_s
EXEC dbo.Fin_DiaLoja_comercial_VW
EXEC dbo.estado_sub_grupo_trib_int
EXEC dbo.dia_item_loja_i_200904_new
EXEC dbo.vw_mes_vencimento
EXEC dbo.tipo_faixa
EXEC dbo.limpa_ppcp
EXEC dbo.PK__semestre__0FED2634
EXEC dbo.R_185_estacao
EXEC dbo.SIG_Usuarios
EXEC dbo.CustoUltimaEntradaMMS_ALFREDO
EXEC dbo.VW_LAST6MONTHS
EXEC dbo.periodo_estilo_loja_i_comercial_200905_view
EXEC dbo.XPKentrada_cd_detal
EXEC dbo.XPKlk_grupo_despesa
EXEC dbo.sp_reestruturacao_quinzena_secao_200208_u
EXEC DSS.sp_carga_coordenador
EXEC dbo.lk_sexo_cliente
EXEC dbo.vw_mes_sub_classe_tdloja_tdforn_origem
EXEC RPCUSER.sp_dwh_InseriOrcamento_comercial_i
EXEC dbo.Fin_DiaLojaPagtoDiacCarta_comercial_VW
EXEC dbo.dia_secao_loja_200904_view
EXEC dbo.vw_ano_vencimento
EXEC dbo.tipo_feriado
EXEC dbo.sp_acha_compr_mixfam_fornec_s
EXEC dbo.R_188_grente
EXEC dbo.dia_item_loja_i_200810_new
EXEC dbo.xpkc_periodo_item_loja_i_comercial_ptmp
EXEC dbo.sp_agregacoes_log_u
EXEC dbo.periodo_estilo_loja_i_comercial_200906_view
EXEC dbo.R_25
EXEC dbo.sp_semana_comercial_itemloja_i_new
EXEC dbo.sp_reestruturacao_quinzena_secao_200209_u
EXEC DSS.sp_carga_colaborador
EXEC dbo.lk_status_cartao_cliente
EXEC dbo.proc_atualiza_giro
EXEC dbo.vw_numero_mes
EXEC DSS.sp_dwh_InseriOrcamento_i
EXEC dbo.mes_similar_loja_forn_ped
EXEC dbo.estilo_loja_corrente
EXEC dbo.quinzena_item_loja_200904_view
EXEC dbo.vw_dia_chamada
EXEC dbo.tipo_item_tamanho
EXEC dbo.sp_agregacoes_iii_u
EXEC dbo.dia_secao_loja_200703_view
EXEC dbo.XPK_similiar_item
EXEC dbo.R_92
EXEC dbo.dia_secao_loja_200810_view
EXEC dbo.XPKperiodo_sub_depto_loja_Orcamento
EXEC dbo.sp_work_marisa_new_MMS_teste_MES
EXEC dbo.periodo_estilo_loja_i_comercial_200907_view
EXEC dbo.R_31
EXEC dbo.R_28
EXEC dbo.XPKlk_grupo_fornecedor
EXEC dbo.dia_sub_classe_loja_200601_view
EXEC dbo.sp_reestruturacao_quinzena_secao_200210_u
EXEC dbo.lk_sub_classe
EXEC dbo.tcarga_dwh_financ
EXEC dbo.sp_dwh_exclui_previsao_comercial_d
EXEC dbo.vw_orc_despesa
EXEC dbo.grupo_periodo_loja_setor_cobertura_lead_time
EXEC RPCUSER.sp_dwh_InseriOrcamento_i
EXEC dbo.PK_mes_similar_loja_forn_ped
EXEC dbo.quinzena_item_loja_ii_200904_view
EXEC dbo.vw_mes_chamada
EXEC dbo.tipo_moda_item
EXEC dbo.dia_item_loja_t
EXEC dbo.XPK_similiar_item2
EXEC dbo.R_93
EXEC dbo.quinzena_item_loja_200810_view
EXEC DSS.dw_ods_cliente_new
EXEC dbo.periodo_estilo_loja_i_comercial_200908_view
EXEC dbo.R_34
EXEC dbo.R_74
EXEC dbo.xpkc_lk_grupo_loja_mms
EXEC dbo.sp_reestruturacao_quinzena_secao_200211_u
EXEC dbo.sp_carga_ofr
EXEC dbo.lk_sub_depto
EXEC DSS.mes
EXEC dbo.vw_orc_receita
EXEC dbo.PK_grupo_loja_lead_time
EXEC DSS.SP_DWH_INTRA_DTABLOQ_LOJA_S
EXEC dbo.periodo_estilo_loja_forn_ped
EXEC dbo.estoque
EXEC dbo.tipo_venda_SAP
EXEC dbo.vw_ano_chamada
EXEC dbo.tipo_remarcacao
EXEC dbo.sp_posicao_carga_dwh_u
EXEC dbo.dia_item_loja_taux
EXEC dbo.PK__situacao_atraso___13BDB718
EXEC dbo.dia_secao_loja_200603_view
EXEC dbo.R_alt_92
EXEC dbo.quinzena_item_loja_ii_200810_view
EXEC dbo.agregacoes_dwh_log
EXEC dbo.periodo_estilo_loja_i_comercial_200909_view
EXEC dbo.R_37
EXEC dbo.lk_codigo_motivo_devolucao
EXEC dbo.XPKlk_grupo_receita
EXEC dbo.sp_reestruturacao_quinzena_secao_200212_u
EXEC dbo.lk_sub_grupo_trib
EXEC dbo.tmp_carga
EXEC DSS.work_sap_custo_medio_fiscal
EXEC dbo.vw_orc_tributos
EXEC dbo.FK__grupo_loja_lead_time
EXEC DSS.SP_DWH_INTRA_DTABLOQ_LOJA_U
EXEC dbo.PK_mes_comercial_estilo_loja_forn_ped
EXEC dbo.sp_data_ult_pos_estoque_SAP
EXEC dbo.sp_dwh_ajusta_previsao_empresa_comercial_u
EXEC dbo.vw_mes_referencia
EXEC dbo.tipo_venda
EXEC dbo.dia_item_loja_tt
EXEC dbo.sp_transfere_FastLoad_to_sap_carga_u
EXEC dbo.PK__situacao_entrega__14B1DB51
EXEC dbo.R_alt_93
EXEC dbo.periodo_item_loja_cancelamento
EXEC dbo.Usuarios_Logins
EXEC dbo.semana_comercial_item_loja_i_FINAL_view
EXEC dbo.periodo_item_loja_i_comercial_ptmp
EXEC dbo.dia_item_loja_i_200911_new
EXEC dbo.R_166
EXEC dbo.xpkc_lk_codigo_motivo_devolucao
EXEC dbo.XPKlk_grupo_tributario
EXEC dbo.sp_reestruturacao_quinzena_secao_200301_u
EXEC DSS.sp_carga_processo_furto
EXEC dbo.lk_sub_secao
EXEC dbo.dia_sub_classe_loja_200903_view
EXEC dbo.R_206
EXEC dbo.vw_pedidos
EXEC DSS.vw_loja_mms
EXEC DSS.SP_DWH_INTRA_ESTAT_MOV_DIA
EXEC dbo.periodo_estilo_toda_loja_forn_ped
EXEC RPCUSER.estoque_inicial
EXEC dbo.s_dwh_previsao_empresa_comercial_s
EXEC dbo.tipo_venda_extranet
EXEC dbo.sp_atualiza_cancelamento_venda_financeiro_s
EXEC dbo.dia_item_loja_venda
EXEC dbo.PK__situacao_estrutu__15A5FF8A
EXEC dbo.R_134
EXEC dbo.CMPultimaentradamms
EXEC dbo.spr_Dia_D
EXEC dbo.quinzena_item_loja_200911_view
EXEC dbo.R_168
EXEC dbo.dia_sub_classe_loja_200610_view
EXEC RPCUSER.MargemNegativaSAP188
EXEC dbo.XPKlk_hora
EXEC dbo.sp_reestruturacao_quinzena_secao_200302_u
EXEC DSS.sp_carga_ocorrencia
EXEC dbo.lk_sub_setor
EXEC dbo.dia_sub_classe_loja_200904_view
EXEC dbo.R_207
EXEC dbo.vw_periodo_ano
EXEC dbo.dia_item_loja_i_200805_new
EXEC DSS.SP_DWH_INTRA_MOV_S
EXEC dbo.PK_mes_comercial_estilo_toda_loja_forn_ped
EXEC dbo.periodo_item_loja_ii_stg
EXEC RPCUSER.tmp_carga
EXEC dbo.sp_atualiza_cliente_dwh_u
EXEC dbo.periodo_classe_loja_est
EXEC dbo.XPKsituacao_periodo
EXEC dbo.R_136
EXEC dbo.xpkc_CMPultimaentradamms
EXEC dbo.quinzena_item_loja_ii_200911_view
EXEC dbo.R_55
EXEC dbo.PK__lk_instrucao_cli__3D6081D7
EXEC dbo.sp_reestruturacao_quinzena_secao_200303_u
EXEC dbo.vw_trimestra_comercial
EXEC dbo.lk_supervisor_loja
EXEC dbo.dia_sub_classe_loja_200905_view
EXEC dbo.R_208
EXEC dbo.vw_periodo_comercial_sub_depto_loja_Orcamento
EXEC dbo.dia_secao_loja_200805_view
EXEC dbo.sp_dwh_lead_time_s
EXEC dbo.mes_plfam_loja_forn_ped
EXEC dbo.faixa_est_ped_secao
EXEC dbo.sp_atualiza_venda_prevista_setor_u
EXEC dbo.dia_item_loja_i_200802_new
EXEC dbo.toda_faixa_ticket
EXEC dbo.xpkc_periodo_classe_loja_est2
EXEC dbo.XPKsolicitacao
EXEC dbo.R_137
EXEC dbo.movto_inventario_sap_vw
EXEC dbo.XPKposicao_atual_produto_loja
EXEC dbo.velocidade2
EXEC dbo.sp_carga_orcamento_calendario_civil_pege_dw_i
EXEC dbo.periodo_sub_classe_loja_i_new
EXEC dbo.dia_secao_loja_200911_view
EXEC dbo.R_59
EXEC dbo.XPKlk_item
EXEC dbo.sp_reestruturacao_quinzena_secao_200304_u
EXEC DSS.vw_periodo_calendario_comercial
EXEC dbo.lk_terceiro
EXEC dbo.dia_sub_classe_loja_200906_view
EXEC dbo.R_226
EXEC dbo.quinzena_item_loja_200805_view
EXEC dbo.sp_dwh_lead_time_u
EXEC dbo.PKC_mes_plfam_loja_forn_ped
EXEC dbo.dia_sub_classe_loja_200606_view
EXEC dbo.dia_comercial_item_loja_i_200712_view
EXEC dbo.toda_loja
EXEC dbo.XPKsolicitado
EXEC dbo.R_230
EXEC dbo.dia_sub_classe_loja_200808_view
EXEC dbo.xpkc_posicao_carga_dwh
EXEC dbo.sp_veloc_vendas_u
EXEC dbo.periodo_sub_classe_loja_ii
EXEC dbo.venda_diaitempontopromcli_pricepoint
EXEC dbo.R_62
EXEC dbo.XPKlk_item_tamanho
EXEC dbo.sp_reestruturacao_quinzena_secao_200305_u
EXEC DSS.dw_ctb_mes_carteira
EXEC dbo.lk_tipo_conta_corrente_cliente
EXEC dbo.dia_sub_classe_loja_200907_view
EXEC dbo.R_229
EXEC dbo.dia_comercial_item_loja_i_200607_view
EXEC dbo.vw_presenca_movtos_vendas
EXEC dbo.quinzena_item_loja_ii_200805_view
EXEC DSS.SP_dwh_Load_Orcamento_s
EXEC dbo.mes_comercial_sub_classe_loja_forn_ped
EXEC dbo.faixa_preco
EXEC dbo.dia_comercial_item_loja_ii_200712_view
EXEC dbo.toda_prox_loja
EXEC dbo.sp_data_ult_pos_estoque
EXEC dbo.dia_comercial_classe_toda_loja_est
EXEC dbo.PARA_DELETAR_periodo_comercial_item_loja_sap_02_02_2009_BKP
EXEC dbo.XPKsub_grupo_trib
EXEC dbo.R_190_setor
EXEC dbo.dia_sub_classe_loja_200809_view
EXEC dbo.pk_posicao_financ_secao_loja
EXEC dbo.periodo_sub_classe_toda_loja_i_new
EXEC DSS.dia_secao_loja_200911_view
EXEC dbo.R_126
EXEC dbo.XPKlk_local
EXEC dbo.sp_reestruturacao_quinzena_secao_200306_u
EXEC DSS.dw_ctb_mes_cltot
EXEC dbo.lk_tipo_despesa
EXEC DSS.DECOM_liquidacao_inverno_2009_sem_sul_periodo_5_2009_MG
EXEC dbo.R_209
EXEC dbo.dia_comercial_sub_classe_loja_i_200607_view
EXEC dbo.vw_quinz_plfam_tdloja_tdforn_tdped
EXEC dbo.dia_comercial_item_loja_i_200803_view
EXEC DSS.SP_dwh_Load_Orcamento2_s
EXEC dbo.PKC_mes_comercial_sub_classe_loja_forn_ped
EXEC dbo.faixa_ticket
EXEC dbo.vw_periodo_comercial_fechado
EXEC dbo.periodo_item_loja_i_final_200412
EXEC dbo.dia_comercial_sub_classe_loja_i_200712_view
EXEC dbo.toda_regiao_comercial
EXEC dbo.sp_atualiza_itemdwh_u
EXEC dbo.dia_comercial_classe_loja_est
EXEC dbo.dia_loja_faixa_ticket
EXEC DSS.vw_dia_item_loja_corrente_sap
EXEC dbo.XPKsub_tipo_solicitacao
EXEC dbo.R_191_sub_setor
EXEC dbo.z5758SAP
EXEC dbo.pk_posicao_financeira_item_loja
EXEC dbo.semana_comercial_estilo_loja_i_new_stg
EXEC dbo.periodo_sub_classe_toda_loja_ii
EXEC dbo.R_129
EXEC RPCUSER.custo_unitario_medio_item_mms_historico_marisa_BKP
EXEC dbo.PK__lk_loja__1AD4C8FB
EXEC dbo.sp_reestruturacao_quinzena_secao_200307_u
EXEC DSS.dw_ctb_mes_tipo
EXEC dbo.lk_tipo_imovel_cliente
EXEC dbo.dia_item_loja_i_200908_new
EXEC dbo.R_210
EXEC dbo.periodo_item_loja_i_200607_view
EXEC dbo.vw_quinz_secao_tdloja_tdforn_tdped
EXEC dbo.dia_comercial_item_loja_ii_200803_view
EXEC DSS.sp_dwh_loja_s
EXEC dbo.mes_comercial_sub_classe_tdloja_forn_ped
EXEC dbo.faixas_dias_entrega
EXEC dbo.periodo_item_loja_i_final_view_tmp
EXEC dbo.periodo_item_loja_i_200712_view
EXEC dbo.toda_regiao_comercial_mms
EXEC dbo.dia_loja_toda_faixa_ticket
EXEC RPCUSER.dia_todo_prod_loja_sap_BKP
EXEC dbo.XPKsupervisor_loja
EXEC dbo.R_192_secao
EXEC dbo.xpkc_z5758SAP
EXEC dbo.xpkc_posicao_mms
EXEC dbo.periodo_sub_depto_loja_orcamento
EXEC dbo.dia_sub_classe_loja_200911_view
EXEC dbo.R_138
EXEC dbo.xpkc_lk_loja_faixa_preco_id_faixa
EXEC dbo.sp_reestruturacao_quinzena_secao_200308_u
EXEC DSS.dw_ctb_mes_periodo
EXEC dbo.lk_tipo_item_tamanho
EXEC dbo.quinzena_item_loja_200908_view
EXEC dbo.R_211
EXEC dbo.vw_quinz_ult_pos_estoq
EXEC dbo.dia_comercial_sub_classe_loja_i_200803_view
EXEC DSS.sp_dwh_loja_u
EXEC dbo.PK_mes_comercial_sub_classe_tdloja_forn_ped
EXEC dbo.preco_venda_regular_mms
EXEC dbo.quinz_sub_classe_tdloja_tdforn_tdped
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200712_view
EXEC dbo.todo_fornecedor
EXEC dbo.sp_dwh_dia_calendario_comercial_u
EXEC dbo.dia_comercial_item_loja_i_200701_view
EXEC dbo.dia_loja_todo_prod_cancelamento_venda_siv
EXEC DSS.PARA_DELETAR_tmp_cli_promo_maio
EXEC dbo.XPKsupervisor_regional
EXEC dbo.R_193_gerente_compra
EXEC dbo.xpkc_prazo_permanencia_todo_produto_dia_loja
EXEC dbo.venda_mes_comercialestilopontopromcli_pricepoint
EXEC dbo.classexgrupo_despesa
EXEC dbo.XPKlk_lote_cd
EXEC RPCUSER.produtos_reprocessar
EXEC dbo.sp_reestruturacao_quinzena_secao_200309_u
EXEC dbo.lk_toda_promocao
EXEC dbo.quinzena_item_loja_ii_200908_view
EXEC dbo.R_202
EXEC dbo.vw_quinzena_prev_entr
EXEC dbo.periodo_item_loja_i_200803_view
EXEC DSS.SP_DWH_MVACI_LOJA_U
EXEC dbo.mes_plfam_tdloja_forn_ped
EXEC dbo.sp_atualiza_eventos_regulares_mms_dwh_u
EXEC dbo.quinzena_ITEM_LOJA_ii
EXEC dbo.semana_comercial_item_loja_i_200712_view
EXEC dbo.todo_pedido
EXEC dbo.sp_atualiza_posicao_carga_dwh_u
EXEC dbo.dia_comercial_item_loja_ii_200701_view
EXEC dbo.dia_loja_venda_extranet2
EXEC dbo.xpkc_tipo_faixa
EXEC dbo.dia_comercial_sub_classe_loja_ii
EXEC dbo.R_195
EXEC DSS.contagem_estoque_coletor_vw
EXEC dbo.PK__price_point__1D7C2B7C
EXEC dbo.semana_comercial_estilo_loja_i_new
EXEC dbo.FK__venda_mes__id_ma__1D92D0C3
EXEC dbo.R_274
EXEC dbo.custo_unitario_medio_item_mms_marisa_taquarada_antonio_carlos
EXEC dbo.XPKlk_manifesto_carga
EXEC RPCUSER.xpkc_produtos_reprocessar
EXEC dbo.sp_reestruturacao_quinzena_secao_200310_u
EXEC dbo.lk_toda_reg_geogr_cd
EXEC dbo.dia_secao_loja_200908_view
EXEC dbo.R_203
EXEC dbo.dia_secao_loja_200609_view
EXEC dbo.vw_situacao_pedidos
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200803_view
EXEC DSS.SP_DWH_MVOTOACI_LOJA_S
EXEC dbo.PK_mes_plfam_tdloja_forn_ped
EXEC dbo.fornecedor_principal
EXEC dbo.loja_atributos
EXEC dbo.todo_produto
EXEC dbo.sp_atualiza_previsao_prox_30_u
EXEC dbo.dia_comercial_sub_classe_loja_i_200701_view
EXEC dbo.CustoUltimaEntradaMMS_FULL_WAGNER
EXEC dbo.XPKtipo_feriado
EXEC dbo.dia_comercial_sub_classe_toda_loja_i_new
EXEC dbo.R_181_seto_subsetor
EXEC dbo.venda_periodo_inventario_loja_secao
EXEC dbo.XPKprice_point_grupo_loja_seca
EXEC dbo.vw_posicao_mms
EXEC dbo.semana_comercial_estilo_loja_i_ptmp
EXEC dbo.sp_Inventario_Aprova
EXEC dbo.xpkc_custo_unitario_medio_item_mms_marisa_taquarada_antonio_carlos
EXEC dbo.XPKlk_meio_pagto
EXEC dbo.sp_reestruturacao_quinzena_secao_200311_u
EXEC dbo.lk_toda_reg_geogr_fabricante
EXEC dbo.vw_situcao_atrazo_pedido
EXEC dbo.semana_comercial_item_loja_i_200803_view
EXEC dbo.SP_DWH_PESQUISA_LOJA_S
EXEC dbo.funcionario
EXEC dbo.dia_comercial_item_loja_i_200605_view
EXEC dbo.PK__loja_atributos__2E285FE8
EXEC dbo.todo_tempo
EXEC dbo.sp_atualiza_price_point_u
EXEC dbo.periodo_item_loja_i_200701_view
EXEC dbo.PK__tipo_item_tamanh__1F2F69C4
EXEC dbo.dia_comercial_todo_prod_loja_i_new
EXEC dbo.R_alt_48
EXEC dbo.xpck_venda_periodo_inventario_loja_secao
EXEC dbo.xpkc_processo_carga_dwh_status
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200704_view
EXEC dbo.custo_unitario_medio_item_mms_MARISA
EXEC dbo.sp_Inventario_Cadastra
EXEC dbo.dia_comercial_item_loja_i_200609_view
EXEC dbo.sp_reestruturacao_quinzena_secao_200312_u
EXEC dbo.lk_toda_reg_geogr_fornecedor
EXEC dbo.vw_tod_tempo_prev_entr
EXEC DSS.tmp_venda_ano_anterior
EXEC dbo.SP_DWH_PESQUISA_PREVISAO_S
EXEC DSS.DECOM_clientes_MODA_CASA_JANEIRO2009
EXEC dbo.periodo_item_loja_i_200605_view
EXEC DSS.DECOM_estilos_promocao_2008_compras_analise_pic
EXEC dbo.trimestre
EXEC RPCUSER.sp_atualiza_venda_extranet_dwh_bcp
EXEC dbo.XPKtipo_moda_item
EXEC dbo.dia_comercial_todo_prod_loja_ii
EXEC dbo.R_alt_50
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200705_view
EXEC dbo.xpkc_custo_unitario_medio_item_mms_MARISA
EXEC dbo.sp_Inventario_SelecionaLoja
EXEC dbo.dia_comercial_item_loja_ii_200609_view
EXEC dbo.XPKlk_negocio_loja
EXEC dbo.sp_reestruturacao_quinzena_secao_200401_u
EXEC dbo.lk_toda_reg_geogr_local
EXEC dbo.vw_todo_fornecedor
EXEC DSS.DECOM_estilos_promocao_2008_analise_transito_v002
EXEC dbo.SP_DWH_PLAN_CALENDARIO_S
EXEC dbo.dia_secao_loja_200706_view
EXEC dbo.dia_item_loja_i_200905_new
EXEC dbo.dia_comercial_sub_classe_loja_i_200605_view
EXEC dbo.dia_item_loja_i_200803_new
EXEC dbo.trimestre_estilo_estado_i_new
EXEC dbo.sp_atualptovenda_d
EXEC dbo.PK__tipo_remarcacao__2117B236
EXEC dbo.dia_feriado_todaloja
EXEC dbo.R_alt_60
EXEC dbo.dia_comercial_item_loja_i_200611_view
EXEC dbo.log_pedidos_estoque_back
EXEC dbo.xpk_promocao
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200706_view
EXEC dbo.posicao_atual_produto_loja
EXEC dbo.custo_unitario_medio_item_mms_historico_Marisa
EXEC dbo.dia_calendario_comercial_ii
EXEC dbo.dia_comercial_sub_classe_loja_i_200609_view
EXEC dbo.sp_reestruturacao_quinzena_secao_200402_u
EXEC dbo.lk_toda_reg_geogr_transp
EXEC dbo.vw_trabalho
EXEC DSS.vw_notas_em_transito
EXEC dbo.SP_DWH_PLAN_PERIODOS_S
EXEC dbo.gerente
EXEC dbo.dia_secao_loja_200905_view
EXEC dbo.dia_comercial_item_loja_i_200801_view
EXEC dbo.trimestre_estilo_estado_ii
EXEC dbo.sp_baldinho_d
EXEC dbo.XPKtipo_venda
EXEC dbo.R_alt_61
EXEC dbo.dia_comercial_item_loja_ii_200611_view
EXEC dbo.pk_log_pedidos_estoque_back
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200707_view
EXEC dbo.posicao_carga_dwh
EXEC dbo.MargemNegativaSAP
EXEC dbo.periodo_item_loja_i_200609_view
EXEC DSS.margemnegativasap_vw
EXEC dbo.PK__lk_ocupacao__2959892A
EXEC dbo.sp_reestruturacao_quinzena_secao_i_final_u
EXEC dbo.dia_secao_loja_200707_view
EXEC dbo.lk_todo_cliente
EXEC dbo.lk_lead_time
EXEC dbo.SP_DWH_PLAN_SETORES_S
EXEC dbo.gerente_compra
EXEC dbo.quinzena_item_loja_200905_view
EXEC dbo.dia_comercial_item_loja_ii_200801_view
EXEC dbo.sp_baldinho_i
EXEC DSS.DECOM_estilos_com_data_entrada_entre_jan2001_dez_2006_pos_prom
EXEC dbo.xpkc_toda_faixa_ticket
EXEC dbo.R_alt_63
EXEC dbo.dia_comercial_sub_classe_loja_i_200611_view
EXEC dbo.estoque_nao_enviado_sap_TMP
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200708_view
EXEC dbo.posicao_financ_secao_loja
EXEC dbo.xpkc_MargemNegativaSAP_NEW
EXEC DSS.margemnegativasap_empresa_vw
EXEC dbo.PK__lk_origem_cadast__23A0AFD4
EXEC dbo.sp_reestruturacao_vendas_promocao_price_point_u
EXEC dbo.lk_todo_fornecedor
EXEC DSS.PRC_CONTROLE_CARGA_ATM_old
EXEC dbo.xpkc_lk_lead_time
EXEC DSS.sp_dwh_plan_venda_loja_nova_setor_s
EXEC dbo.grupo_inter_com
EXEC dbo.quinzena_item_loja_ii_200905_view
EXEC dbo.dia_comercial_sub_classe_loja_i_200801_view
EXEC dbo.trimestre_estilo_loja_i_new
EXEC dbo.sp_reestruturacao_pedidos_u
EXEC dbo.sp_baldinho_s
EXEC dbo.XPKtoda_loja
EXEC dbo.R_alt_64
EXEC dbo.periodo_item_loja_i_200611_view
EXEC dbo.XPKproximidade_loja_
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200709_view
EXEC dbo.posicao_financeira_item_loja
EXEC dbo.PK__lk_plano__245E3335
EXEC dbo.lk_tipo_praca
EXEC dbo.sp_reestruturacao_vendas_promocao_u
EXEC dbo.lk_todo_item
EXEC dbo.dia_comercial_item_loja_i_200906_view
EXEC DSS.notas_em_transito_vw
EXEC dbo.sp_dwh_planejamento_carga_venda_s
EXEC dbo.grupo_lead_time
EXEC DSS.sp_dwh_previsao_semana_comercial_sub_depto_loja_i
EXEC dbo.periodo_item_loja_i_200801_view
EXEC dbo.trimestre_estilo_loja_ii
EXEC dbo.sp_baldinho_u
EXEC dbo.sp_devolve_desc_periodo_comercial
EXEC dbo.XPKtoda_prox_loja
EXEC dbo.R_alt_65
EXEC dbo.PK_quinz_plfam_tdloja_tdforn_tdped
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200710_view
EXEC DSS.venda_nl_dia_sub_classe_loja
EXEC dbo.custo_marisa_atacadista_congelado
EXEC dbo.XPKlk_ponto_venda
EXEC dbo.PK__LK_TIPO_PRACA__255322C5
EXEC dbo.lk_todo_ponto_venda
EXEC dbo.periodo_item_loja_i_200906_view
EXEC dbo.lk_grupo_climatico
EXEC DSS.sp_dwh_planejamento_carga_venda_s
EXEC dbo.dia_comercial_item_loja_i_200704_view
EXEC dbo.grupo_secao_faixa_preco
EXEC DSS.sp_dwh_seleciona_loja_nova_s
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200801_view
EXEC dbo.sp_CalculoAbertoPrevisto_s
EXEC dbo.dia_item_loja_ii_final
EXEC dbo.xpkc_toda_regiao_comercial_mms
EXEC dbo.R_49
EXEC dbo.XPKquinzena
EXEC dbo.posicao_mms
EXEC dbo.lk_tipo_motivo_desconto_vw
EXEC dbo.xpkc_custo_marisa_atacadista_congelado
EXEC dbo.faixa_price_point
EXEC dbo.XPKlk_promocao
EXEC dbo.sp_refresh_virtual_s
EXEC dbo.lk_todo_produto
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200906_view
EXEC dbo.xpkc_lk_grupo_climatico
EXEC DSS.sp_dwh_planejamento_estrategico_s
EXEC dbo.dia_comercial_item_loja_ii_200704_view
EXEC dbo.grupo_setor
EXEC dbo.dia_comercial_item_loja_i_200903_view
EXEC dbo.semana_comercial_item_loja_i_200801_view
EXEC dbo.trimestre_estilo_toda_loja_i_new
EXEC dbo.sp_carga_cd_s
EXEC dbo.sp_barreto_s
EXEC DSS.previsao_venda_dia_comercial_secao_tmp
EXEC dbo.PK__todo_pedido__26D08B8C
EXEC dbo.R_94
EXEC dbo.XPKquinzena_anterior
EXEC DSS.dw_cag_log_new
EXEC dbo.prazo_permanencia_todo_produto_dia_loja
EXEC dbo.lk_tipo_evento_preco_vw
EXEC dbo.Fin_DiaLoja
EXEC dbo.XPKlk_quinzena
EXEC dbo.sp_refresh_virtual
EXEC dbo.lk_todo_tempo
EXEC dbo.dia_comercial_item_loja_ii_200906_view
EXEC dbo.movtos_pendentes_processamento
EXEC DSS.sp_dwh_planejamento_venda_comercial_s
EXEC dbo.dia_comercial_sub_classe_loja_i_200704_view
EXEC dbo.grupo_tributario
EXEC dbo.dia_comercial_item_loja_ii_200903_view
EXEC DSS.lc_dia_emissao_fatura
EXEC DSS.DECOM_estilos_promocao_2008_vamos_vender_tudo
EXEC dbo.trimestre_estilo_toda_loja_ii
EXEC dbo.sp_carga_clc_d
EXEC dbo.XPKtodo_produto
EXEC dbo.R_alt_90
EXEC dbo.lk_tef_vw
EXEC dbo.Fin_DiaLojaBanco
EXEC dbo.lk_loja_praca
EXEC dbo.sp_RelAcompSecao_s
EXEC dbo.posicao_estoque_TMP
EXEC dbo.lk_todo_transportador
EXEC dbo.semana_comercial_item_loja_i_200906_view
EXEC dbo.grupo_periodo_setor_cobertura_lead_time
EXEC dbo.xpkc_movtos_pendentes_processamento
EXEC DSS.sp_dwh_planejamento_venda_s
EXEC dbo.periodo_item_loja_i_200704_view
EXEC dbo.hora
EXEC dbo.dia_comercial_sub_classe_loja_i_200903_view
EXEC dbo.VW_CRED_faturamento
EXEC dbo.quinzena_item_loja_200712_view
EXEC dbo.sp_carga_dwh_processos_adicionais_s
EXEC dbo.XPKtrimestre
EXEC dbo.sp_dwh_previsao_semana_comercial_sub_depto_loja_i
EXEC dbo.R_alt_91
EXEC dbo.lk_promocao_vw
EXEC dbo.dia_secao_loja_200611_view
EXEC dbo.Fin_DiaLojaBancoTerc
EXEC dbo.PK__lk_loja_praca__2923B3A9
EXEC dbo.sp_RelIdadeProduto_s
EXEC dbo.lk_transportador
EXEC dbo.dia_comercial_sub_classe_loja_i_200906_view
EXEC dbo.PK__grupo_periodo_se__5B1014F8
EXEC dbo.sp_atualiza_movtos_pendentes_processamento_u
EXEC DSS.sp_dwh_ultima_cotacao_s
EXEC dbo.sp_pedidos_u_VB
EXEC dbo.inventario_distribuido_mensal
EXEC dbo.periodo_item_loja_i_200903_view
EXEC dbo.VW_CRED_faturamento_toda_conta
EXEC dbo.quinzena_item_loja_ii_200712_view
EXEC dbo.trimestre_sub_classe_loja_i_new
EXEC dbo.sp_carga_estoque_reservado_i
EXEC dbo.previsao_venda_dia_comercial_secao
EXEC dbo.XPKtrimestre_estilo_estado_i_new
EXEC dbo.R_alt_94
EXEC dbo.estoque_SAP_FLASH
EXEC dbo.lk_periodo_faixa_cupom_vw
EXEC dbo.Fin_DiaLojaCartao
EXEC dbo.sp_saoVendas_s
EXEC RPCUSER.vw_posicao_estoque
EXEC dbo.lk_transportador_base
EXEC dbo.sp_carga_pedido_MMS_d_BKP
EXEC dbo.FK__grupo_per__id_su__5CF85D6A
EXEC DSS.sp_dwh_verba_s
EXEC dbo.sp_pedidos_i_VB
EXEC dbo.inventario_loja
EXEC dbo.lk_cidade_cd
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200903_view
EXEC dbo.quinzena_item_loja_200801_view
EXEC dbo.trimestre_sub_classe_loja_ii
EXEC dbo.sp_carga_financeiro_i
EXEC dbo.dia_item_loja_i_200902_new
EXEC dbo.XPKtrimestre_estilo_estado_ii
EXEC dbo.xpkc_estoque_SAP_FLASH
EXEC dbo.dia_secao_loja_200602_view
EXEC dbo.lk_origem_cliente_vw
EXEC dbo.Fin_DiaLojaDesp
EXEC dbo.sp_saoVendasLojas_s
EXEC dbo.posicao_estoque_MMS
EXEC dbo.lk_trimestre
EXEC dbo.sp_carga_pedido_MMS_i_bkp
EXEC dbo.xpkc_dia_secao_loja_i_comercial_ptmp
EXEC DSS.sp_dwh_verba_u
EXEC dbo.f_capacidade_loja_depto_sub_depto_classe_eqpt
EXEC dbo.item
EXEC dbo.XPKlk_cidade_cd
EXEC dbo.semana_comercial_item_loja_i_200903_view
EXEC dbo.quinzena_item_loja_ii_200801_view
EXEC dbo.ucusto
EXEC dbo.sp_reestruturacao_dia_secao_200409_u
EXEC dbo.sp_carga_financeiro_i2
EXEC dbo.quinzena_item_loja_200902_view
EXEC RPCUSER.57Santin
EXEC DSS.dw_cac_log_temp2
EXEC dbo.price_point
EXEC dbo.lk_operador_caixa_vw
EXEC dbo.Fin_DiaLojaDespTerc
EXEC dbo.XPKlk_regiao_comercial
EXEC dbo.sp_secao_s
EXEC dbo.xpkc_posicao_estoque_MMS
EXEC RPCUSER.lkcr2
EXEC dbo.sp_dw_CargaPedidos_Agrega_MMS_i_BKP
EXEC dbo.sp_dwhCargaCusto_u
EXEC dbo.l_areavenda_classe
EXEC dbo.R_15
EXEC dbo.xpkc_saldo_estoque_sap
EXEC dbo.quinzena_item_loja_200802_view
EXEC dbo.ucusto2
EXEC dbo.sp_reestruturacao_dia_secao_200410_u
EXEC dbo.sp_carga_financeiro_i3
EXEC dbo.quinzena_item_loja_ii_200902_view
EXEC dbo.XPKtrimestre_estilo_loja_i_new
EXEC dbo.estoque_nao_enviado_sap_Z57Z58
EXEC dbo.price_point_grupo_loja_secao
EXEC dbo.lk_motivo_desconto_vw
EXEC dbo.XPKlk_regiao_geogr_cd
EXEC dbo.sp_secoes_mico_s
EXEC dbo.dia_sub_classe_loja_200609_view
EXEC dbo.lk_tipo_movto_pendentes_processamento
EXEC dbo.sp_dwhCargaCustoZero_u
EXEC dbo.item_loja_corrente
EXEC dbo.R_18
EXEC dbo.sp_dw_CargaPedidos_MMS_i
EXEC dbo.quinzena_item_loja_ii_200802_view
EXEC dbo.ucusto2t
EXEC dbo.sp_carga_financeiro_i3_bkp
EXEC dbo.vw_semana_ano
EXEC dbo.dia_secao_loja_200902_view
EXEC dbo.XPKtrimestre_estilo_loja_ii
EXEC dbo.dia_comercial_item_loja_i_200602_view
EXEC dbo.dia_item_loja_ii
EXEC dbo.xpkc_estoque_nao_enviado_sap_Z57Z58
EXEC dbo.price_point_loja_secao
EXEC dbo.lk_motivo_cancelamento_vw
EXEC dbo.cliente_ocupacao_temp
EXEC dbo.XPKlk_regiao_geogr_fabricante
EXEC dbo.sp_secoes_s
EXEC dbo.posicao_estoque_VIP
EXEC RPCUSER.log_pedidos_estoque2
EXEC dbo.VW_CRED_fatos_venda
EXEC dbo.xpkc_LK_tipo_movto_pendentes_processamento
EXEC dbo.XPKdia_semana
EXEC dbo.sp_dwhvendas_s
EXEC dbo.R_20
EXEC dbo.lk_estilo
EXEC dbo.quinzena_item_loja_200803_view
EXEC dbo.sp_carga_financeiro_t
EXEC dbo.dia_comercial_item_loja_i_200812_view
EXEC dbo.periodo_item_loja_i_200602_view
EXEC dbo.FK__mes__id_semestre__2E91A8E5
EXEC dbo.ods_cred21
EXEC dbo.processo_carga_dwh_descricao
EXEC dbo.lk_forma_pagto_vw
EXEC DSS.sp_seleciona_loja_s
EXEC RPCUSER.posicao_estoque_VIP2
EXEC dbo.log_previsao_venda_comercial
EXEC DSS.prc_controle_carga_atm
EXEC dbo.VW_CRED_vw_primeira_compra_dia_filiacao
EXEC dbo.PK__dia_semana_anter__2F10CBD2
EXEC dbo.IS_SESSION_FACT
EXEC dbo.sp_estoq_log_refresh_s
EXEC dbo.eqpt
EXEC dbo.item_tamanho
EXEC dbo.R_14
EXEC dbo.dft_descr_fornec_princ
EXEC dbo.quinzena_item_loja_ii_200803_view
EXEC dbo.ucustot2
EXEC dbo.sp_carga_loja_d
EXEC dbo.dia_secao_loja_200704_view
EXEC dbo.dia_comercial_item_loja_ii_200812_view
EXEC dbo.XPKtrimestre_estilo_toda_loja_i_new2
EXEC dbo.dia_comercial_sub_classe_loja_i_200602_view
EXEC dbo.R_438
EXEC dbo.lk_faixa_cupom_vw
EXEC dbo.XPKlk_regiao_geogr_local
EXEC dbo.sp_SelecionaDadosCarteira_s
EXEC dbo.dia_comercial_item_loja_i_200705_view
EXEC dbo.dia_comercial_sub_depto_toda_loja_est
EXEC dbo.VW_CRED_lc_local_transacao
EXEC dbo.XPKdia_sub_depto_loja_Orcamento
EXEC dbo.sp_exclui_previsao_comercial_d
EXEC dbo.PK__Eqpt__64C39C64
EXEC dbo.lk_adm_cartao
EXEC dbo.R_24
EXEC dbo.DF__lk_estilo__id_te__2E49F227
EXEC RPCUSER.Planejamento_dw_empresa
EXEC dbo.ultimo_mes_ano
EXEC dbo.sp_carga_loja_u
EXEC dbo.dia_comercial_sub_classe_loja_i_200812_view
EXEC dbo.XPKtrimestre_estilo_toda_loja_ii2
EXEC dbo.R_6
EXEC dbo.previsao_venda_periodo_secao
EXEC dbo.lk_evento_preco_vw
EXEC dbo.XPKlk_regiao_geogr_loja
EXEC dbo.sp_SelecionaDadosEstoque_s
EXEC dbo.dia_comercial_item_loja_ii_200705_view
EXEC dbo.VW_CRED_lc_mes_transacao
EXEC dbo.sp_agregacoes_u
EXEC dbo.xpkc_dia_sub_depto_loja_est
EXEC dbo.sp_FeriadoLoja_s
EXEC dbo.Sub_Eqpt
EXEC dbo.lk_ano
EXEC dbo.lk_fabricante_para_fornecedor
EXEC dbo.XPKlk_estilo
EXEC DSS.mes_loja_orcamento
EXEC dbo.unidade
EXEC dbo.periodo_item_loja_i_200812_view
EXEC dbo.R_434
EXEC dbo.Sandro_inventario
EXEC dbo.lk_cliente_geral_vw
EXEC dbo.XPKC_Venda_MessecaoPontoPromCli_PricePoint2
EXEC dbo.Fin_DiaLojaTerc
EXEC dbo.XPKlk_regiao_geogr_transp
EXEC dbo.sp_SelecionaDetalheCarteira_s
EXEC dbo.dia_comercial_sub_classe_loja_i_200705_view
EXEC dbo.loja_faixa_preco
EXEC DSS.mkt_campanha_dias_criancas_2009_SALEM
EXEC dbo.VW_CRED_lc_dia_transacao
EXEC dbo.sp_atualiza_data_ultima_entrada_transf_cd_lead_time
EXEC dbo.sp_fornec_comprador_s
EXEC dbo.PK__Sub_Eqpt__62DB53F2
EXEC dbo.lk_area
EXEC dbo.XPKlk_fabricante_para_fornecedor
EXEC dbo.item2
EXEC DSS.DECOM_estilos_promocao_2008_presidente_urgente_20080324
EXEC dbo.usaldo
EXEC dbo.sp_carga_orcamento_receitas_i
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200812_view
EXEC dbo.XPKtrimestre_sub_classe_loja_i_new
EXEC dbo.R_435
EXEC dbo.PARA_DELETAR_Venda_DiaItemPontoPromCliPagto_Cartao
EXEC DSS.dw_cac_log_temp
EXEC dbo.promocao
EXEC dbo.venda_item_loja_cupom_vw
EXEC dbo.R_404
EXEC dbo.PK__grupo_inter_com
EXEC dbo.grupo_price_point
EXEC dbo.XPKlk_secao
EXEC dbo.sp_SelecionaSecao_s
EXEC dbo.periodo_item_loja_i_200705_view
EXEC dbo.VW_CRED_vw_primeira_compra_n_dias_filiacao
EXEC dbo.xpkc_dia_sub_depto_toda_loja_est
EXEC DSS.sp_intraSeleconaLojaSuperv_s
EXEC dbo.config_eqpt
EXEC dbo.lk_banco
EXEC dbo.DF__item2__id_tema__2C61A9B5
EXEC dbo.dia_secao_loja_200607_view
EXEC DSS.DECOM_estilos_promocao_2008_analise_transito
EXEC dbo.usuarios_45_dias
EXEC dbo.sp_carga_orcamento_tributos_i
EXEC dbo.semana_comercial_item_loja_i_200812_view
EXEC dbo.XPKtrimestre_sub_classe_loja_ii
EXEC DSS.r_275
EXEC dbo.produtos_excluidos_custo_SAP
EXEC DSS.venda_nl_dia_sub_classe_loja_II
EXEC dbo.R_128
EXEC dbo.XPKfornecedor_principal
EXEC dbo.icm_cd_loja
EXEC dbo.PK__lk_semana_ano__33A076C5
EXEC dbo.sp_SelecionaSetor_s
EXEC dbo.sp_inventario_i
EXEC dbo.PK__Config_Eqpt__33E1393E
EXEC dbo.lk_banco_empresa_custodia
EXEC dbo.XPKCitem
EXEC dbo.dia_curva_venda_calendario_civil
EXEC dbo.velocidade
EXEC dbo.sp_carga_pedido_d
EXEC dbo.dia_comercial_item_loja_i_200702_view
EXEC dbo.vm_coordenadores
EXEC dbo.XPKultimo_mes_ano
EXEC dbo.xpkc_sandro_inventario
EXEC dbo.venda_diaitempontopromclipagto_t
EXEC dbo.R_135
EXEC dbo.XPKlk_fabricante
EXEC dbo.XPKlk_semana_mes
EXEC dbo.sp_SelecionaTotalCarteira_s
EXEC dbo.R_223
EXEC dbo.sp_Item_Similar_s
EXEC dbo.lk_cartao
EXEC dbo.FK_classe_x_item
EXEC dbo.ucustot
EXEC dbo.xpkc_dia_curva_venda_calendario_civil
EXEC dbo.sp_carga_pedido_i
EXEC dbo.dia_comercial_item_loja_ii_200702_view
EXEC dbo.XPKunidade
EXEC dbo.produtos_excluidos_custo_SAP_bkp
EXEC dbo.xpkc_dia_item_loja_i_comercial_ptmp
EXEC dbo.proximidade_loja
EXEC dbo.R_278_despesa
EXEC dbo.XPKlk_grupo_fabricante
EXEC dbo.XPKlk_semestre
EXEC dbo.sp_SelVendaFinanceira_s
EXEC dbo.lojas_migradas
EXEC DSS.meta_classificao_preco_periodo_secao
EXEC dbo.R_224
EXEC dbo.xpkc_dia_toda_loja_todo_prod_cancelamento_venda_SIV
EXEC dbo.sp_jda_estoque_dia_loja_s
EXEC dbo.lk_cartaocredito_financeira
EXEC dbo.sp_work_marisa_new
EXEC dbo.FK_depto_x_item
EXEC dbo.lojas_venda_dinamica
EXEC DSS.CLIENTE_NOVO
EXEC dbo.venda_prevista_setor
EXEC dbo.sp_carga_venda_agregacoes_u
EXEC dbo.dia_comercial_sub_classe_loja_i_200702_view
EXEC dbo.dia_sub_classe_loja_200810_view
EXEC dbo.xpk_usaldo
EXEC dbo.PARA_DELETAR_Venda_DiaSecaoLojaPromCli
EXEC dbo.CMPultimaentradamms_historico
EXEC dbo.quinz_plfam_tdloja_tdforn_tdped
EXEC RPCUSER.bts_venda_nl_ol_scl_carga
EXEC dbo.R_279_despesa
EXEC dbo.XPKlk_setor
EXEC DSS.sp_siv_seleciona_loja_nova_s
EXEC dbo.margem_pricepoint
EXEC dbo.R_225
EXEC dbo.xpk_dia_toda_loja_venda_extranet2
EXEC dbo.lk_cd
EXEC dbo.FK_grupo_setor_x_item
EXEC dbo.venda_projetada
EXEC dbo.sp_reestruturacao_dia_secao_200411_u
EXEC dbo.periodo_item_loja_i_200702_view
EXEC dbo.venda_diasecaopontopromclipagto
EXEC dbo.xpkc_CMPultimaentradamms_historico
EXEC dbo.quinzena
EXEC dbo.R_281_despesa
EXEC dbo.dia_sub_classe_loja_200611_view
EXEC dbo.PK__lk_sexo__2B41D19C
EXEC dbo.mes
EXEC DSS.meta_linha_produto_periodo_secao
EXEC dbo.fk_lk_tema_x_lk_todo_tema
EXEC dbo.dia_comercial_item_loja_i_200608_view
EXEC dbo.dia_item_loja_i_200806_new
EXEC dbo.sp_quinzenaitemloja_iii_new
EXEC dbo.lk_centro_responsabilidade
EXEC dbo.FK_item_tamanho_x_item
EXEC dbo.sp_reestruturacao_dia_secao_200412_u
EXEC dbo.sp_carga_venda_prom_d
EXEC RPCUSER.custo_unitario_medio_item_mms_taxmdp_historico_BKP_impostos_errados_mms
EXEC dbo.dia_sub_classe_loja_200811_view
EXEC dbo.PK_Descontos
EXEC dbo.dia_secao_loja_200701_view
EXEC dbo.venda_diatodoprodpontopromclipagto
EXEC dbo.sp_atualiza_CMPultimaentradamms
EXEC dbo.quinzena_anterior
EXEC dbo.periodo_item_toda_loja_i_new
EXEC dbo.PK__lk_status_cartao__38652BE2
EXEC dbo.mes_anter_sol
EXEC dbo.tmp_istitular
EXEC dbo.FK__Loja_seto__id_gr__38852773
EXEC dbo.dia_comercial_sub_classe_loja_i_200608_view
EXEC dbo.dia_secao_loja_200806_view
EXEC dbo.PKC_dia_todoprod_loja_iii
EXEC dbo.sp_limpa_iii_d
EXEC dbo.FK_moda_item_x_item
EXEC DSS.dia_loja_venda_extranet_civil_vw
EXEC dbo.work_movto_venda
EXEC dbo.sp_reestruturacao_dia_secao_200501_u
EXEC dbo.sp_carga_venda_prom_u
EXEC dbo.dia_sub_classe_loja_200812_view
EXEC dbo.dia_item_loja_ii_final_200502
EXEC dbo.venda_diatodoprodpontopromtodoclipagto
EXEC DSS.movto_inventario_sap_vw_tmp
EXEC dbo.BTS_VENDA_NL_OL_SCL
EXEC dbo.XPKlk_sub_classe
EXEC dbo.mes_anterior
EXEC dbo.dia_comercial_item_loja_i_200907_view
EXEC dbo.periodo_item_loja_i_200608_view
EXEC dbo.quinzena_item_loja_200806_view
EXEC dbo.custo_unitario_produto_atacadista
EXEC dbo.sp_limpeza_vendas_s
EXEC dbo.venda_unitaria_item_loja_AUDITORIA
EXEC dbo.fk_origem_item_x_item
EXEC dbo.quinzena_item_loja_final_200502
EXEC dbo.xpk_id_conta
EXEC dbo.sp_carga_venda_agregacoestop_u
EXEC dbo.dia_sub_classe_loja_200901_view
EXEC dbo.dia_loja_venda_extranet_comercial
EXEC dbo.venda_diatodoprodtodopontopromclipagto
EXEC dbo.dia_item_loja_i_200811_new
EXEC dbo.bts_venda_nl_ol_scl_new
EXEC dbo.periodo_item_toda_loja_ii
EXEC dbo.XPKlk_sub_depto
EXEC dbo.periodo_item_loja_i_200907_view
EXEC dbo.dia_item_loja_ii_comercial_ptmp
EXEC dbo.quinzena_item_loja_ii_200806_view
EXEC dbo.PKC_custo_unitario_produto_atacadista
EXEC dbo.sp_ListaItemComprLoja_s
EXEC dbo.xpkc_venda_unitaria_item_loja_AUDITORIA
EXEC dbo.lk_cidade_fabricante
EXEC dbo.sp_local_autom_s
EXEC dbo.FK_sub_classe_x_item
EXEC dbo.quinzena_item_loja_i_final
EXEC dbo.sp_carga_venda_loja_u
EXEC dbo.dia_sub_classe_loja_200902_view
EXEC dbo.DF__fin_dialo__EVend__4E60F0A7
EXEC dbo.dia_secao_loja_200604_view
EXEC dbo.venda_mesitempontopromcli_pricepoint
EXEC dbo.dia_secao_loja_200811_view
EXEC dbo.dia_item_loja_i_final_200502
EXEC dbo.xpkc_bts_venda_nl_ol_scl_new
EXEC dbo.dia_comercial_item_loja_i_200610_view
EXEC dbo.XPKlk_sub_grupo_trib
EXEC dbo.sp_SelecionaLoja_s
EXEC dbo.mes_comercial_sub_classe_loja_tdforn_origem
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200907_view
EXEC dbo.xpkc_dia_item_loja_ii_comercial_ptmp
EXEC dbo.PKC_dia_todo_prod_toda_loja_i
EXEC dbo.sp_listalojas_proximidade_s
EXEC dbo.FK_sub_depto_x_item
EXEC dbo.VW_CRED_VW_conta
EXEC dbo.sp_carga_venda_u
EXEC dbo.DF__fin_dialo__Sfalt__5AC6C78C
EXEC dbo.venda_mesitemtodopontopromcli_pricepoint
EXEC dbo.quinzena_item_loja_200811_view
EXEC DSS.dw_ods_cliente
EXEC dbo.dia_item_loja_i_new
EXEC dbo.sp_atualiza_venda_nl_ol_scl_DWH
EXEC dbo.dia_comercial_item_loja_ii_200610_view
EXEC dbo.XPKlk_sub_secao
EXEC dbo.dia_comercial_item_loja_ii_200907_view
EXEC dbo.dia_comercial_item_loja_i_200804_view
EXEC dbo.sp_listalojas_s
EXEC dbo.lk_cidade_local
EXEC dbo.FK_tipo_item_tamanho_x_item
EXEC dbo.VW_CRED_lc_dia_emissao_fatura
EXEC dbo.cad_clientes_tmp
EXEC dbo.PK__Faixa_price_poin__3C9FD11A
EXEC dbo.SP_CargaFeriado_U
EXEC dbo.vm_lojas_coordenadores_tmp
EXEC dbo.DF__Fin_DiaLo__ERece__196D3A24
EXEC dbo.venda_messecaopontopromcli_pricepoint
EXEC dbo.quinzena_item_loja_ii_200811_view
EXEC dbo.dia_secao_bcp
EXEC dbo.xpkc_BTS_VENDA_NL_OL_SCL
EXEC dbo.dia_comercial_sub_classe_loja_i_200610_view
EXEC dbo.comparativo_CMP
EXEC dbo.XPKlk_sub_setor
EXEC RPCUSER.tbl_limpar
EXEC dbo.mes_comercial_sub_classe_tdloja_tdforn_origem
EXEC dbo.semana_comercial_item_loja_i_200907_view
EXEC dbo.dia_comercial_item_loja_ii_200804_view
EXEC dbo.sp_loadfaixa_i
EXEC dbo.sp_audit_extrai_rodes
EXEC dbo.lk_cidade_loja
EXEC dbo.FK_todo_item_x_item
EXEC dbo.VW_CRED_limite_credito_conta
EXEC dbo.cad_cac_log
EXEC dbo.XPKFin_DiaLoja
EXEC dbo.sp_carrega_orcamento_i
EXEC dbo.vm_lojas_coordenadores
EXEC dbo.venda_messecaotodopontopromtodocli_pricepoint
EXEC dbo.dia_sub_classe_loja_200708_view
EXEC dbo.BTS_VENDA_NL_OL_SDE
EXEC dbo.R_100
EXEC dbo.periodo_item_loja_i_200610_view
EXEC dbo.xpkc_comparativo_CMP
EXEC dbo.XPKlk_supervisor_loja
EXEC dbo.xpkc_posicao_estoque_VIP
EXEC dbo.mes_comercial_sub_classe_tdloja_tdforn_tdped
EXEC dbo.dia_comercial_sub_classe_loja_i_200907_view
EXEC dbo.dia_comercial_sub_classe_loja_i_200804_view
EXEC dbo.sp_loadfx_i
EXEC DSS.l_faixa_horaPP
EXEC dbo.lk_cidade_transp
EXEC dbo.FK_unidade_x_item
EXEC dbo.XPKFin_DiaLojaBanco
EXEC RPCUSER.Custo_SAP_teste
EXEC dbo.PARA_DELETAR_Venda_mesSimilarTodoPontoTodaPromTodoCli_PricePoint
EXEC dbo.dia_comercial_item_loja_i_200809_view
EXEC dbo.xpkc_BTS_VENDA_NL_OL_SDE
EXEC dbo.R_101
EXEC dbo.comparativo_CMP_200808
EXEC dbo.XPKlk_terceiro
EXEC dbo.sp_dwm_inclui_gerente
EXEC DSS.mes_cotacao_moeda
EXEC dbo.lk_num_dias_credito
EXEC dbo.dia_item_loja_i_200909_new
EXEC dbo.periodo_item_loja_i_200804_view
EXEC dbo.PK__dias_cobertura_estoques
EXEC dbo.custo_unitario_item_loja
EXEC dbo.sp_loadprecosconcor_u
EXEC DSS.PK__l_faixa_horaPP__3F52EBEA
EXEC dbo.lk_classe
EXEC dbo.R_75
EXEC dbo.XPKFin_DiaLojaBancoTerc
EXEC dbo.sp_dwh_log_previsao_comercial_i
EXEC dbo.dia_sub_classe_loja_200703_view
EXEC dbo.dia_comercial_item_loja_ii_200809_view
EXEC dbo.xpkc_periodo_item_loja_cancelamento
EXEC dbo.xpkc_comparativo_CMP_200808
EXEC dbo.PK__lk_tipo_conta_co__40064DAA
EXEC dbo.sp_dwm_altera_gerente
EXEC dbo.XPKlk_num_dias_credito
EXEC dbo.quinzena_item_loja_200909_view
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200804_view
EXEC dbo.PK__dias_entrega__403B57D4
EXEC dbo.PKCcusto_unitario_item_loja
EXEC dbo.sp_loadprecosconcor2_u
EXEC dbo.lk_classe_despesa
EXEC dbo.quinzena_item_loja_i_ptmp
EXEC dbo.XPKFin_DiaLojaCartao
EXEC dbo.sp_carrega_previsao_comercial_u
EXEC dbo.DF__Fin_DiaLo__EDocC__4F5514E0
EXEC dbo.dia_comercial_sub_classe_loja_i_200809_view
EXEC DSS.dbo.venda_item_loja_cupom_vw
EXEC dbo.R_103
EXEC dbo.dia_secao_loja_200612_view
EXEC DSS.lk_cliente_cadastro
EXEC dbo.XPK_lk_tipo_despesa
EXEC RPCUSER.sp_teste
EXEC dbo.sp_dwm_lista_gerente
EXEC dbo.mes_estilo_estado_i_new
EXEC dbo.Fin_DiaLojaPagtoDiacTerc
EXEC dbo.quinzena_item_loja_ii_200909_view
EXEC dbo.FK_SIG_Grupo_Links_1
EXEC dbo.semana_comercial_item_loja_i_200804_view
EXEC dbo.xpkc_distrito_comercial_mms
EXEC dbo.sp_loadtodafaixa_i
EXEC dbo.lk_classe_receita
EXEC dbo.quinzena_item_loja_ii_ptmp
EXEC dbo.XPKFin_DiaLojaDesp
EXEC dbo.DF__Fin_DiaLo__SReto__50493919
EXEC dbo.FK__price_poi__id_gr__41A47D59
EXEC dbo.semana_calendario_comercial
EXEC dbo.periodo_item_loja_i_200809_view
EXEC dbo.sp_plan_devolve_semana_comercial
EXEC dbo.periodo_item_loja_i_new_Exp
EXEC dbo.R_109
EXEC dbo.comparativo_CMP_Escribano
EXEC dbo.PK__lk_tipo_imovel__2E1E3E47
EXEC dbo.sp_ticketOK_fx_s
EXEC dbo.sp_dwm_inclui_superv_regional
EXEC dbo.mes_estilo_estado_ii
EXEC dbo.XPKFin_DiaLojaPagtoDiacTerc
EXEC dbo.dia_secao_loja_200909_view
EXEC dbo.FK_SIG_Grupo_Links_2
EXEC dbo.sp_loadtodafx_i
EXEC dbo.estilo_negocio_corrente
EXEC dbo.XPKFin_DiaLojaDespTerc
EXEC dbo.R_585
EXEC dbo.xpkc_semana_calendario_comercial
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200809_view
EXEC dbo.sp_plan_previsao_s
EXEC DSS.dw_ods_cliente_temp
EXEC DSS.semana_comercial_item_loja_i_200909_view
EXEC dbo.R_88
EXEC dbo.xpkc_comparativo_CMP_Escribano
EXEC dbo.XPKlk_tipo_item_tamanho
EXEC dbo.sp_ticketOK_s
EXEC dbo.sp_dwm_altera_superv_regional
EXEC dbo.PARA_DELETAR_mes_estilo_estado_iii_new
EXEC dbo.R_196
EXEC dbo.Saldo_Estoque_SAP_ERRO
EXEC dbo.FK_Grupos_Usuarios_1
EXEC dbo.last_day
EXEC dbo.sp_loja_similar_mico_s
EXEC dbo.lk_cliente
EXEC dbo.estilo_estado_corrente
EXEC dbo.sp_carrega_previsao_u
EXEC dbo.FK__quinzena__id_sem__438CC5CB
EXEC dbo.DF__semana_ca__ID_SE__438D9122
EXEC dbo.semana_comercial_item_loja_i_200809_view
EXEC dbo.lk_cob_tipo_produto_vw
EXEC dbo.R_alt_100
EXEC dbo.XPKlk_toda_promocao
EXEC dbo.sp_ultima_data_estoque_s
EXEC dbo.mes_estilo_loja_i_new
EXEC dbo.R_197
EXEC dbo.TMP_VENDA_PROMOCAO
EXEC dbo.FK_Grupos_Usuarios_2
EXEC dbo.dia_sub_classe_loja_200805_view
EXEC dbo.XPKestacao
EXEC dbo.sp_maxcusto_estado_u
EXEC dbo.lk_cliente_cartao
EXEC dbo.sp_carrega_reservatorio_i
EXEC dbo.R_433
EXEC dbo.vw_dia_comercial_anterior
EXEC DSS.movto_inventario_sap_cmp_forcado_z57_vw
EXEC DSS.dw_ods_cliente_oracle
EXEC dbo.lk_cob_tipo_cobradora_vw
EXEC dbo.R_alt_84
EXEC dbo.margem_sap_moda
EXEC dbo.XPKlk_toda_reg_geogr_cd
EXEC dbo.sp_usuarios_45_dias_s
EXEC dbo.sp_dwm_lista_superv_regional
EXEC dbo.mes_estilo_loja_ii
EXEC dbo.R_221
EXEC DSS.ncs_event_falta
EXEC dbo.FK__Venda_Dia__id_pr__1117EB45
EXEC dbo.dia_sub_classe_loja_200806_view
EXEC dbo.XPKestacao_ano
EXEC dbo.sp_mes_mix_familia_todalojavenda_i
EXEC DSS.usp_ExampleProc
EXEC dbo.R_68
EXEC dbo.dia_sub_classe_loja_200612_view
EXEC dbo.spBTSInserePedidos_MMS_DWH
EXEC dbo.Planejamento_semana_comercial_dw
EXEC dbo.lk_cob_situacao_acordo_vw
EXEC dbo.R_alt_88
EXEC dbo.sp_gera_bkp_planejamento_200610_s
EXEC dbo.xpkc_margem_sap_moda
EXEC dbo.XPKlk_toda_reg_geogr_fabricante
EXEC dbo.sp_veloc_vendas_periodo_u
EXEC dbo.PARA_DELETAR_mes_estilo_loja_iii_new
EXEC dbo.Fin_DiaLojaPagtoDiacCartaoTerc
EXEC dbo.dia_item_loja_sap_carga_TESTE
EXEC dbo.FK__Venda_Mes__id_ma__45DF2291
EXEC DSS.vw_movtos_pendentes_processamento
EXEC dbo.xpkc_estado_sub_grupo_trib
EXEC dbo.sp_mes_pl_familia_loja_orcamento_i
EXEC dbo.lk_cliente_cartao_titular
EXEC dbo.R_7
EXEC dbo.dia_sub_classe_loja_200701_view
EXEC dbo.tbEstimulo_pedido_MMS_DW
EXEC dbo.lk_cob_posicao_cobranca_vw
EXEC dbo.XPKlk_toda_reg_geogr_fornecedor
EXEC dbo.sp_veloc_vendas_u_OLD
EXEC dbo.sp_dwm_define_gerente_loja
EXEC dbo.mes_estilo_toda_loja_i_new
EXEC dbo.NULL4
EXEC dbo.lk_mes
EXEC dbo.FK__Venda_Mes__id_ma__46D346CA
EXEC dbo.xpkc_estado_sub_grupo_trib_int
EXEC dbo.sp_meta_venda_s
EXEC dbo.lk_comprador
EXEC dbo.sp_carrega_tbl_particionada_i
EXEC dbo.R_382
EXEC DSS.inventario_prevencao
EXEC dbo.DF_tbEstimulo_pedido_MMS_DW_Tipo
EXEC dbo.dw_cac_log_tmp
EXEC dbo.lk_cob_origem_pgto_vw
EXEC dbo.R_17
EXEC dbo.XPKlk_toda_reg_geogr_local
EXEC dbo.sp_veloc_vendas_u_meses
EXEC dbo.sp_dwm_recupera_gerente_loja
EXEC dbo.mes_estilo_toda_loja_ii
EXEC dbo.Zero_Value6
EXEC dbo.XPKlk_mes
EXEC dbo.FK__Venda_Mes__id_ma__47C76B03
EXEC dbo.sp_minvenda_estado_quinz_u
EXEC dbo.lk_condicao_pagto
EXEC dbo.PK_cad_clientes
EXEC dbo.XPKFin_DiaLojaTerc
EXEC dbo.sp_reprocessa_quinzena_gamba
EXEC dbo.sp_carregavendas_i
EXEC dbo.quinzena_item_loja_iii_new
EXEC dbo.R_383
EXEC dbo.dia_item_loja_ii_inventario
EXEC dbo.spBTSEstimulaPedidoAprovado
EXEC dbo.lk_cob_faixa_atraso_vw
EXEC dbo.R_alt_19
EXEC dbo.XPKlk_toda_reg_geogr_transp
EXEC dbo.sp_dwm_lista_gerente_loja
EXEC dbo.PARA_DELETAR_mes_estilo_toda_loja_iii_new
EXEC dbo.Zero_Value7
EXEC dbo.R_alt_95
EXEC dbo.FK__Venda_Mes__id_ma__48BB8F3C
EXEC DSS.vw_kar_estoque_fim_mes
EXEC dbo.sp_movtoinventario_s
EXEC dbo.lk_depto
EXEC dbo.PK__Grupo_price_poin__4905A7FF
EXEC dbo.sp_checadados_s
EXEC dbo.57Santin_200901
EXEC dbo.xpkc_dia_item_loja_ii_INVENTARIO
EXEC RPCUSER.57santin_200810
EXEC dbo.dw_ods_cliente_outubro
EXEC dbo.lk_cob_tipo_recebimento_vw
EXEC dbo.R_175
EXEC dbo.lk_lojas_antigas_atuais
EXEC dbo.XPKlk_TODO_cliente
EXEC dbo.sp_verifica_curva_venda_comercial
EXEC dbo.XPKFin_DiaLojaPagtoDiacCartaoTerc
EXEC dbo.R_alt_96
EXEC dbo.FK__Venda_Mes__id_ma__49AFB375
EXEC DSS.vw_kar_loja_item_estoque_fim_mes
EXEC dbo.xpkc_faixa_est_ped_pl_familia
EXEC dbo.sp_MProp_AgregaCompras_u
EXEC dbo.lk_despesa
EXEC dbo.sp_checadados_s2
EXEC dbo.dia_item_loja_i_final_new
EXEC dbo.vw_dia_item_loja_nfcompra
EXEC RPCUSER.57santin_200810_510
EXEC DSS.DECOM_estilos_estoque_mais_noventa_dias_nov2009
EXEC dbo.R_177
EXEC dbo.XPKlk_tod_fornecdor
EXEC dbo.dia_sub_classe_loja_200707_view
EXEC dbo.R_184
EXEC dbo.R_96
EXEC dbo.FK__Venda_mes__id_ma__4AA3D7AE
EXEC DSS.vw_kar_loja_estilo_estoque_fim_mes
EXEC dbo.SP_DWH_INTRA_VENDA_DIA_ANTERIOR_LOJA_S
EXEC dbo.sp_compr_fornec_item_loja_s
EXEC dbo.sp_btz_extrai_clientesfull
EXEC DSS.vw_dia_item_loja_nfcompra
EXEC dbo.PARA_DELETAR_dia_loja_venda_extranet2_bkp
EXEC dbo.sp_upgraddiagrams
EXEC dbo.XPKlk_todo_item
EXEC dbo.R_188
EXEC dbo.R_alt_82
EXEC dbo.FK__Venda_mes__id_ma__4B97FBE7_
EXEC dbo.semana_comercial_item_loja_ii_stg
EXEC dbo.XPKfaixa_ticket
EXEC dbo.sp_MProp_VendaEstoque_i
EXEC dbo.sp_compr_fornec_item_loja3_s
EXEC dbo.lk_tipo_inventario
EXEC dbo.mes_item_loja_sap_vw
EXEC dbo.PARA_DELETAR_dia_toda_loja_venda_extranet2_bkp
EXEC dbo.sysdiagrams
EXEC dbo.XPKlk_todo_produto
EXEC dbo.R_190
EXEC dbo.R_alt_86
EXEC dbo.FK__cobertura__id_gr__4C8C2020
EXEC DSS.dia_item_loja_sap_carga_vw
EXEC dbo.PK__faixas_dias_entr__4CA12EB9
EXEC dbo.sp_MProp_Tudo_i
EXEC dbo.sp_compr_fornec_item_loja4_s
EXEC dbo.xpkc_lk_tipo_inventario
EXEC dbo.sp_verifica_erro_carga
EXEC dbo.R_30
EXEC dbo.PK__sysdiagrams__4D4C0586
EXEC dbo.CMP_SAP
EXEC dbo.XPKlk_todo_tempo
EXEC dbo.R_193
EXEC dbo.R_106
EXEC dbo.tb_custo_importados
EXEC dbo.sp_mpvenda_s
EXEC dbo.dia_item_loja_i_200906_new
EXEC dbo.sp_comprador_item_loja_s
EXEC dbo.custo_easy_corrente
EXEC dbo.sp_SAP_I_CO_01_s
EXEC dbo.quinzena_item_negocio_i_new
EXEC dbo.R_403
EXEC dbo.semana_comercial_item_loja_i_ptmp
EXEC dbo.PRC_spaceused
EXEC dbo.R_33
EXEC dbo.UK_principal_name
EXEC dbo.xpkc_CMP_SAP
EXEC dbo.XPKlk_todo_transportador
EXEC dbo.dia_item_loja_ii_final_stg
EXEC dbo.R_198
EXEC dbo.R_102
EXEC dbo.FK__cobertura__id_me__4E746892
EXEC dbo.xpkc_tb_custo_importados
EXEC dbo.sp_ncs_verifica_evento
EXEC dbo.dia_secao_loja_200906_view
EXEC dbo.sp_reprocessa_quinzena_gamba_200410
EXEC dbo.sp_comprador_mixfamilia_s
EXEC dbo.dw_ods_cliente_while
EXEC dbo.xpck_custo_easy_corrente
EXEC dbo.dia_secao_negocio_i_new
EXEC dbo.quinzena_item_negocio_ii
EXEC dbo.xfkc_regiao_comercial_mms_x_toda_regiao_comercial_mms
EXEC dbo.semana_comercial_item_loja_i_200608_view
EXEC dbo.periodo_item_loja_i_new_stg
EXEC DSS.DECOM_estilos_estoque_mais_noventa_dias_nov2009_v2
EXEC dbo.R_165
EXEC dbo.sp_helpdiagrams
EXEC dbo.prc_atualiza_CMP_SAP_DWH
EXEC dbo.XPKlk_transportador
EXEC dbo.venda_diaitempontopromclipagto
EXEC dbo.quinzena_item_loja_i_final_new
EXEC dbo.R_219
EXEC dbo.R_alt_99
EXEC dbo.FK__cobertura__id_su__4F688CCB
EXEC dbo.DF_tb_custo_importados_dt_entrada
EXEC DSS.sp_ncs_verifica_evento
EXEC dbo.quinzena_item_loja_200906_view
EXEC dbo.sp_comprador_mixsubfamilia_s
EXEC dbo.PK_dw_ods_cliente_while
EXEC dbo.custo_easy_corrente_history
EXEC dbo.dia_secao_negocio_ii
EXEC dbo.quinzena_item_negocio_iii_new
EXEC dbo.R_233
EXEC dbo.semana_comercial_item_loja_i_200609_view
EXEC RPCUSER.dia_teste_falta
EXEC dbo.periodo_item_loja_i_new
EXEC dbo.R_58
EXEC dbo.sp_helpdiagramdefinition
EXEC dbo.dia_item_loja_i_200809_new
EXEC dbo.XPKlk_transportador_base
EXEC dbo.Fin_DiaLojaPagtoDiacCartao
EXEC dbo.dia_comercial_item_loja_i_200908_view
EXEC dbo.r_275
EXEC DSS.DECOM_estilos_promocao_liquidacao_inverno_2008
EXEC dbo.XPKfuncionario
EXEC dbo.sp_ncs_verifica_evento_falta
EXEC dbo.quinzena_item_loja_ii_200906_view
EXEC dbo.sp_reprocessa_quinzena_gamba_200411
EXEC dbo.sp_ConsultaVendaLoja_s
EXEC dbo.xpck_custo_easy_corrente_history
EXEC dbo.PK_dia_secao_negocio_ii
EXEC dbo.quinzena_item_todaloja_i_new
EXEC dbo.R_44
EXEC dbo.semana_comercial_item_loja_i_200610_view
EXEC dbo.dia_item_loja_i_200812_new
EXEC dbo.periodo_item_loja_ii
EXEC DSS.lk_faixa_desconto_vw
EXEC dbo.R_alt_56
EXEC dbo.sp_creatediagram
EXEC dbo.dia_secao_loja_200809_view
EXEC dbo.XPKlk_trimestre
EXEC dbo.sp_atualiza_local_dwh_u
EXEC dbo.XPKFin_DiaLojaPagtoDiacCartao
EXEC dbo.periodo_item_loja_i_200908_view
EXEC dbo.FK__dia__id_semestre__5150D53D
EXEC DSS.DECOM_estilos_anterior_2007_promocao_inverno_2008
EXEC dbo.sp_parametrosdwh_s
EXEC dbo.lk_dia
EXEC dbo.dia_comercial_item_loja_i_200904_view
EXEC dbo.grupo_setor_dias_entrega_lead_time
EXEC DSS.sp_contaesubconta_s
EXEC dbo.sp_atualiza_custo_easy_corrente
EXEC dbo.quinzena_item_todaloja_ii
EXEC dbo.R_45
EXEC dbo.semana_comercial_item_loja_i_200611_view
EXEC dbo.dia_secao_loja_200812_view
EXEC dbo.periodo_item_loja_ii_ptmp
EXEC dbo.dia_item_loja_i_200912_new
EXEC dbo.sp_renamediagram
EXEC dbo.quinzena_item_loja_200809_view
EXEC dbo.R_240
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200908_view
EXEC dbo.xfk_dia_x_semana_ano
EXEC dbo.sp_perc_pos_movtos
EXEC dbo.lk_empresa_custodia
EXEC dbo.dia_comercial_item_loja_ii_200904_view
EXEC dbo.PK__grupo_setor_dias__527ACEF7
EXEC dbo.xpkc_LK_Tema
EXEC dbo.sp_reprocessa_quinzena_gamba200412
EXEC dbo.PARA_DELETAR_sp_cprot_venda_extranet
EXEC dbo.CMP_SAP_historico_BKP
EXEC dbo.dia_secao_loja_i_new
EXEC dbo.quinzena_item_todaloja_iii_new
EXEC dbo.R_46
EXEC dbo.semana_comercial_item_loja_i_200612_view
EXEC dbo.quinzena_item_loja_200812_view
EXEC dbo.xpkc_periodo_item_loja_ii_ptmp
EXEC dbo.quinzena_item_loja_200912_view
EXEC dbo.sp_alterdiagram
EXEC dbo.quinzena_item_loja_ii_200809_view
EXEC dbo.R_241
EXEC dbo.dia_comercial_item_loja_ii_200908_view
EXEC dbo.R_415
EXEC dbo.XPKgerente
EXEC dbo.sp_previsao_estoque_atual_s
EXEC dbo.lk_estacao
EXEC dbo.dia_comercial_sub_classe_loja_i_200904_view
EXEC dbo.xpkc_LK_todo_Tema
EXEC dbo.sp_custo_unitario_item_loja_medio_CD_i
EXEC dbo.CMP_SAP_corrente_BKP
EXEC dbo.R_alt_47
EXEC dbo.semana_comercial_item_loja_i_200701_view
EXEC dbo.quinzena_item_loja_ii_200812_view
EXEC dbo.dia_comercial_sub_classe_loja_i_200709_view
EXEC dbo.quinzena_item_loja_ii_200912_view
EXEC dbo.sp_dropdiagram
EXEC dbo.dia_comercial_item_loja_i_200807_view
EXEC dbo.xpkc_loja_faixa_preco2
EXEC dbo.xpkc_custo_unitario_medio_item_mms_historico_marisa
EXEC dbo.mes_plfam_loja_tdforn_origem
EXEC dbo.R_242
EXEC dbo.semana_comercial_item_loja_i_200908_view
EXEC dbo.xfkc_distrito_comercial_mms_x_regiao_comercial_mms
EXEC dbo.dia_comercial_item_loja_i_200805_view
EXEC dbo.XPKgerente_compra
EXEC dbo.sp_previsao_estoque_atual_s2
EXEC dbo.periodo_item_loja_i_200904_view
EXEC dbo.FK__grupo_set__id_su__54631769
EXEC dbo.PK__Loja_setor_price__54775AAB
EXEC dbo.sp_reprocessa_quinzena_gamba200501
EXEC dbo.sp_data_carga_clc_u
EXEC dbo.sp_atualiza_cmp_sap_corrente
EXEC dbo.R_alt_70
EXEC dbo.semana_comercial_item_loja_i_200702_view
EXEC dbo.dia_comercial_item_loja_i_200810_view
EXEC dbo.periodo_item_loja_i_200709_view
EXEC dbo.dia_secao_loja_200912_view
EXEC dbo.fn_diagramobjects
EXEC dbo.dia_comercial_item_loja_ii_200807_view
EXEC dbo.xpkc_lojas_migradas
EXEC dbo.sp_vertical_s
EXEC dbo.trimestre_comercial
EXEC dbo.R_243
EXEC dbo.dia_comercial_sub_classe_loja_i_200908_view
EXEC dbo.xfkc_distrito_comercial_mms_x_toda_regiao_comercial_mms
EXEC dbo.dia_comercial_item_loja_ii_200805_view
EXEC dbo.sp_previsao_estoque_atual_s2_tst
EXEC dbo.lk_estado_cd
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200904_view
EXEC dbo.grupo_setor_loja_lead_time
EXEC dbo.sp_data_maxima_carregavel_s
EXEC DSS.movto_inventario_sap_vw_teste
EXEC dbo.R_71
EXEC dbo.semana_comercial_item_loja_i_200703_view
EXEC dbo.dia_comercial_item_loja_ii_200810_view
EXEC DSS.fornecedor_principal_bkp
EXEC dbo.dia_comercial_sub_classe_loja_i_200807_view
EXEC dbo.PK__margem_pricepoin__55F58EC9
EXEC dbo.mes_plfam_tdloja_tdforn_origem
EXEC dbo.R_244
EXEC dbo.dia_comercial_sub_classe_loja_i_200805_view
EXEC dbo.xpkc_grupo_lead_time
EXEC dbo.sp_previsao_estoque_atual_tst_s2
EXEC dbo.lk_estado_civil_cliente
EXEC dbo.semana_comercial_item_loja_i_200904_view
EXEC dbo.PK__grupo_setor_loja__564B5FDB
EXEC dbo.sp_data_ult_pos_estoque_financ
EXEC dbo.DF__venda_per__id_me__56764864
EXEC dbo.semana_comercial_item_loja_i_200704_view
EXEC dbo.dia_comercial_sub_classe_loja_i_200810_view
EXEC dbo.regiao_geografica
EXEC DSS.plan_distribuicao_previsao
EXEC dbo.periodo_item_loja_i_200807_view
EXEC dbo.XPKmes
EXEC dbo.sp_VFinanc_CargaEstoque_i
EXEC dbo.mes_secao_toda_loja_i_new
EXEC dbo.Fin_DiaLojaPagtoDiacBancoTerc
EXEC dbo.dia_item_loja_i_200910_new
EXEC dbo.periodo_item_loja_i_200805_view
EXEC dbo.XPKgrupo_secao_faixa_preco
EXEC dbo.sp_previsao_vendas_distribuicao_autom_s
EXEC dbo.lk_estado_fabricante
EXEC dbo.quinzena_item_loja_ii_final_200502
EXEC dbo.sp_reprocessa_quinzena_gamba_200412
EXEC dbo.sp_data_ult_posic_financ_s
EXEC dbo.R_76
EXEC dbo.semana_comercial_item_loja_i_200705_view
EXEC dbo.periodo_item_loja_i_200810_view
EXEC dbo.XPKregiao_geografica
EXEC dbo.custo_unitario_medio_item_mms_TAXMDP
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200807_view
EXEC dbo.XPKmes_anterior
EXEC dbo.sp_VFinanc_Estoque_i
EXEC dbo.mes_secao_toda_loja_ii
EXEC dbo.XPKFin_DiaLojaPagtoDiacBancoTerc2
EXEC dbo.quinzena_item_loja_200910_view
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200805_view
EXEC dbo.XPKgrupo_setor
EXEC dbo.sp_previsao_vendas_distribuicao_autom_s2
EXEC dbo.FK__grupo_set__id_su__5833A84D
EXEC dbo.quinzena_sub_classe_loja_i_new
EXEC dbo.sp_DataPedido_s
EXEC dbo.dia_item_loja_sap_carga
EXEC dbo.R_77
EXEC dbo.semana_comercial_item_loja_i_200706_view
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200810_view
EXEC dbo.lk_estado
EXEC dbo.xpkc_custo_unitario_medio_item_mms_TAXMDP
EXEC dbo.semana_comercial_item_loja_i_200807_view
EXEC dbo.sp_VFinanc_Estoque_Item_s
EXEC dbo.PARA_DELETAR_mes_secao_toda_loja_iii_new
EXEC dbo.R_187
EXEC dbo.quinzena_item_loja_ii_200910_view
EXEC dbo.semana_comercial_item_loja_i_200805_view
EXEC dbo.XPKgrupo_tributario
EXEC dbo.sp_previsao_vendas_escolha_lojas_s
EXEC dbo.lk_estado_local
EXEC dbo.posicao_venda_atm
EXEC dbo.quinzena_sub_classe_loja_ii
EXEC dbo.sp_reprocessa_quinzena_gamba_200501
EXEC dbo.sp_delvendas_d
EXEC dbo.dia_sub_classe_loja_200704_view
EXEC dbo.dia_secao_loja_200605_view
EXEC dbo.R_79
EXEC dbo.lk_praca_midia
EXEC dbo.semana_comercial_item_loja_i_200810_view
EXEC dbo.XPKestado
EXEC dbo.custo_unitario_medio_item_mms_TAXMDP_historico
EXEC dbo.PK_mes_comercial_sub_classe_loja_tdforn_origem
EXEC dbo.dtproperties
EXEC dbo.R_192
EXEC dbo.dia_secao_loja_200910_view
EXEC dbo.dia_item_loja_i_200807_new
EXEC dbo.PK__hora__59FB29D7
EXEC dbo.sp_previsao_vendas_temp_s
EXEC dbo.lk_estado_loja
EXEC dbo.quinzena_sub_classe_loja_venda
EXEC dbo.sp_descsecao_s
EXEC dbo.dw_ods_cliente_while2
EXEC dbo.dia_comercial_item_loja_i_200603_view
EXEC dbo.quinzena_pvenda_param
EXEC dbo.R_80
EXEC dbo.PK__Lk_Praca_midia__0D90A7CD
EXEC dbo.vw_vendas_por_operador
EXEC dbo.R_16
EXEC dbo.xpkc_custo_unitario_medio_item_mms_TAXMDP_historico_
EXEC dbo.pk_dtproperties
EXEC dbo.R_200
EXEC DSS.PARA_DELETAR_tmp_carlinhos
EXEC dbo.dia_secao_loja_200807_view
EXEC dbo.xpk_inventario_distribuido_mensal
EXEC dbo.sp_Promocao_Dwh_d
EXEC dbo.lk_estado_transp
EXEC dbo.xpkc_posicao_venda_atm
EXEC dbo.semana_mes_prev_entr
EXEC dbo.PK_SDL_MOVTOA
EXEC dbo.sp_dia_pl_setor_loja_orcamento_u
EXEC dbo.PK_dw_ods_cliente_while2
EXEC dbo.dia_secao_loja_sap
EXEC dbo.periodo_item_loja_i_200603_view
EXEC dbo.quinzena_secao_loja_i_new
EXEC dbo.R_29
EXEC DSS.DECOM_estilos_com_data_entrada_entre_jan2001_dez_2006
EXEC RPCUSER.57Santin_200811
EXEC dbo.lk_cidade
EXEC dbo.sp_plan_distribui_ajuste_empresa
EXEC dbo.PK_mes_comercial_sub_classe_tdloja_tdforn_origem
EXEC dbo.periodo_item_loja_i_final_view
EXEC dbo.DF__dtpropert__versi__5BB95517
EXEC dbo.dia_secao_loja_200708_view
EXEC dbo.R_216
EXEC DSS.PARA_DELETAR_tmp_carlinhos_2008
EXEC dbo.quinzena_item_loja_200807_view
EXEC dbo.XPKinventario_loja
EXEC dbo.sp_Promocao_Dwh_i
EXEC dbo.senama_anterior
EXEC dbo.PK_SIG_Grupo_Links
EXEC dbo.semana_comercial_item_loja_sap
EXEC dbo.dia_comercial_sub_classe_loja_i_200603_view
EXEC dbo.quinzena_secao_loja_ii
EXEC dbo.R_462
EXEC dbo.dia_comercial_item_loja_i_200612_view
EXEC dbo.dia_item_loja_i_ptmp_bkp
EXEC dbo.XPKcidade
EXEC dbo.R_173
EXEC DSS.plan_carga
EXEC dbo.PK_mes_comercial_sub_classe_tdloja_tdforn_tdped
EXEC dbo.dt_generateansiname
EXEC dbo.sp_carga_orcamento_mes
EXEC dbo.Fin_DiaLojaPagtoDiacBanco
EXEC DSS.PARA_DELETAR_tmp_carlinhos_2008_loja
EXEC dbo.quinzena_item_loja_ii_200807_view
EXEC dbo.XPKitem
EXEC dbo.sp_Promocao_Dwh_s
EXEC dbo.dia_comercial_item_loja_i_200905_view
EXEC dbo.sub_classe_loja_corrente
EXEC dbo.PK_Grupos
EXEC dbo.alicota_gamba
EXEC RPCUSER.sp_dia_pl_setor_loja_orcamento_u
EXEC dbo.dia_sub_classe_loja_200602_view
EXEC dbo.quinzena_secao_loja_iii_new
EXEC dbo.R_556
EXEC dbo.dia_comercial_item_loja_ii_200612_view
EXEC dbo.R_64
EXEC dbo.R_179
EXEC dbo.dt_adduserobject
EXEC dbo.dia_comercial_item_loja_i_200706_view
EXEC dbo.XPKFin_DiaLojaPagtoDiacBanco
EXEC DSS.PARA_DELETAR_tmp_carlinhos_2009_loja
EXEC dbo.sp_pvenda_s
EXEC dbo.lk_fabricante
EXEC dbo.dia_comercial_item_loja_ii_200905_view
EXEC dbo.sysalternates
EXEC dbo.PK_Grupos_Usuarios
EXEC dbo.xpkc_alicota_gamba
EXEC dbo.sp_dia_secao_toda_loja_u
EXEC dbo.periodo_comercial_item_loja_sap
EXEC dbo.dia_sub_classe_loja_200603_view
EXEC dbo.FK__semestre__id_ano__5E40BC07
EXEC dbo.dia_comercial_sub_classe_loja_i_200612_view
EXEC dbo.R_65
EXEC dbo.R_180
EXEC dbo.XPKmes_estilo_estado_i_new
EXEC dbo.dt_setpropertybyid
EXEC dbo.dia_comercial_item_loja_ii_200706_view
EXEC dbo.mes_sub_classe_estado_i_new
EXEC dbo.R_235
EXEC dbo.quinzena_item_todaloja_i_ptmp
EXEC dbo.dia_comercial_item_loja_ii_200601_view
EXEC DSS.DECOM_estilos_promocao_2008_verao
EXEC dbo.PK__item_tamanho__5EBFDEF4
EXEC dbo.sp_pvenlojaprox_s
EXEC dbo.lk_faixa_limite_cartao
EXEC dbo.dia_comercial_sub_classe_loja_i_200905_view
EXEC dbo.dia_sub_classe_loja_200607_view
EXEC dbo.PK_SIG_LINKS
EXEC dbo.sp_dia_todo_prod_loja_i
EXEC dbo.mes_item_loja_sap
EXEC dbo.dia_sub_classe_loja_200604_view
EXEC dbo.periodo_item_loja_i_200612_view
EXEC dbo.sp_inicializa_margem_negativa
EXEC DSS.LK_CIDADE_FORNECEDOR_BKP
EXEC dbo.R_182
EXEC dbo.XPKmes_estilo_estado_ii
EXEC dbo.dt_getobjwithprop
EXEC dbo.dia_comercial_sub_classe_loja_i_200706_view
EXEC dbo.mes_sub_classe_estado_ii
EXEC dbo.R_236
EXEC dbo.dia_comercial_item_loja_ii_200602_view
EXEC DSS.DECOM_estilos_promocao_2008_inverno
EXEC dbo.XPKlk_adm_cartao
EXEC dbo.sp_pvenmapa
EXEC dbo.lk_faixa_salarial_cliente
EXEC dbo.periodo_item_loja_i_200905_view
EXEC RPCUSER.Temp_previsao
EXEC dbo.PK_SIG_Usuarios
EXEC dbo.sp_dia_todo_prod_loja_iii
EXEC dbo.dw_ods_cliente_while3
EXEC dbo.dia_sub_classe_loja_200605_view
EXEC dbo.dia_classe_loja_est
EXEC dbo.dia_comercial_item_loja_i_200707_view
EXEC dbo.lk_regiao_geogr_fornecedor
EXEC dbo.spr_Busca_Ult_Preco_Venda_S
EXEC dbo.XPKmes_estilo_estado_iii_new
EXEC dbo.dt_getpropertiesbyid
EXEC dbo.periodo_item_loja_i_200706_view
EXEC dbo.PARA_DELETAR_mes_sub_classe_estado_iii_new
EXEC dbo.R_237
EXEC dbo.dia_sub_classe_loja_200909_view
EXEC dbo.xfk_tipo_faixa_pl_familia
EXEC dbo.dia_comercial_item_loja_ii_200603_view
EXEC dbo.XPKlk_ano
EXEC dbo.sp_pvenmapa_resumo_s
EXEC dbo.lk_faixa_ticket
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200905_view
EXEC dbo.vw_3meses_ant
EXEC dbo.PK__Venda_DiaItemPon__0E3B7E9A
EXEC dbo.sp_diaferiadoloja_i
EXEC dbo.PK_dw_ods_cliente_while3
EXEC dbo.R_423
EXEC dbo.xpkc_dia_classe_loja_est
EXEC dbo.Saldo_Estoque_SAP
EXEC dbo.dia_comercial_item_loja_i_200708_view
EXEC dbo.XPKlk_regiao_geogr_fornecedor
EXEC dbo.xfk_Faixa_limite_cartao_x_moeda
EXEC dbo.dia_comercial_item_loja_cancelamento_vw
EXEC dbo.dt_setpropertybyid_u
EXEC dbo.sp_display_comparativo_venda
EXEC dbo.mes_sub_classe_loja_i_new
EXEC dbo.R_238
EXEC dbo.dia_sub_classe_loja_200908_view
EXEC dbo.dia_comercial_item_loja_ii_200604_view
EXEC dbo.PK__lk_area__619C4B9F
EXEC dbo.sp_pvenmapa2_dias
EXEC dbo.lk_forma_pagto
EXEC dbo.semana_comercial_item_loja_i_200905_view
EXEC dbo.vw_3meses_post
EXEC dbo.R_424
EXEC dbo.dia_classe_toda_loja_est
EXEC dbo.dia_comercial_item_loja_i_200709_view
EXEC dbo.R_11
EXEC dbo.dt_getobjwithprop_u
EXEC DSS.DECOM_estilos_PROD_ANTERIOR_A_01_06_2007
EXEC dbo.mes_sub_classe_loja_ii
EXEC dbo.R_239
EXEC dbo.dia_sub_classe_loja_200910_view
EXEC dbo.dia_comercial_item_loja_ii_200605_view
EXEC dbo.XPKlk_banco
EXEC dbo.sp_pvenmapa2_dias_s
EXEC DSS.l_tipo_rodes
EXEC dbo.dia_item_loja_i_200907_new
EXEC dbo.work_sap_custo_medio_fiscal_HISTORICO
EXEC dbo.vw_6meses_ant
EXEC dbo.sp_quinzenaitemloja_i_new
EXEC dbo.dia_todo_prod_loja_sap
EXEC dbo.PK_Usuarios_Logins
EXEC dbo.SDL_MOVTOD3
EXEC dbo.refresh_dimensoes
EXEC dbo.R_337
EXEC dbo.xpkc_dia_classe_toda_loja_est
EXEC dbo.venda_mes_comercialitempontopromclipagto
EXEC dbo.dia_comercial_item_loja_i_200710_view
EXEC dbo.lk_estado_fornecedor
EXEC dbo.XPKmes_estilo_loja_iii_new
EXEC dbo.dt_getpropertiesbyid_u
EXEC DSS.sp_carga_orcamento
EXEC dbo.PARA_DELETAR_mes_sub_classe_loja_iii_new
EXEC dbo.dia_comercial_item_loja_i_200909_view
EXEC dbo.dia_comercial_item_loja_ii_200606_view
EXEC dbo.xpkc_lk_banco_empresa_custodia
EXEC dbo.sp_pvenmapa2_s
EXEC DSS.PK__l_tipo_rodes__63904C60
EXEC dbo.dia_secao_loja_200907_view
EXEC dbo.QueryNotificationErrorsQueue
EXEC dbo.vw_Grupo_inter_com_forn
EXEC dbo.PK__Venda_DiaSecaoLo__63B99E3B
EXEC dbo.sp_periodo_itemloja_i_new
EXEC dbo.dw_ods_cliente_while4
EXEC dbo.xpkc_dia_todo_prod_loja_sap
EXEC dbo.DF_dia_id_semana_mes
EXEC dbo.SDL_MOVTOD2
EXEC dbo.refresh_id_loja_data
EXEC dbo.xfk_id_semestre
EXEC dbo.mes_classe_loja_est
EXEC dbo.venda_mes_comercialitempontopromcli_pricepoint
EXEC dbo.XPKlk_estado_fornecedor
EXEC dbo.XPKmes_estilo_toda_loja_i_new2
EXEC dbo.dt_dropuserobjectbyid
EXEC DSS.log_movto_dw_tot
EXEC dbo.mes_sub_depto_loja_orcamento
EXEC dbo.dia_comercial_item_loja_i_200910_view
EXEC dbo.dia_comercial_item_loja_ii_200607_view
EXEC dbo.XPKlk_cartao
EXEC dbo.sp_quinzena_mix_familia_lojavenda_i
EXEC DSS.l_usuariopp
EXEC dbo.quinzena_item_loja_200907_view
EXEC dbo.vw_Grupo_inter_con_forn
EXEC dbo.XPKC_Venda_MesItemPontoPromCli_PricePoint2
EXEC dbo.sp_reestruturacao_periodo_sub_classe_i_u
EXEC dbo.sp_diaitemlojai_d
EXEC dbo.PK_dw_ods_cliente_while4
EXEC dbo.Saldo_Estoque_SAP_Wagner
EXEC dbo.DF__dia__id_semestre__7DCF4150
EXEC dbo.regiao_comercial
EXEC dbo.xpkc_mes_classe_loja_est2
EXEC dbo.venda_mes_comercialestilopontopromclipagto
EXEC dbo.vw_mes_estilo_loja_dwh_merge
EXEC dbo.pedidos
EXEC dbo.R_12
EXEC dbo.XPKmes_estilo_toda_loja_ii2
EXEC dbo.dt_droppropertiesbyid
EXEC dbo.quinzena_item_loja_ii_final
EXEC dbo.mes_sub_depto_loja_est
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200909_view
EXEC dbo.dia_comercial_item_loja_ii_200608_view
EXEC dbo.PK__lk_cartaocredito__656CDC83
EXEC dbo.sp_quinzena_pvenda_param
EXEC DSS.PK__l_UsuarioPP__657894D2
EXEC dbo.lk_gerente_compra
EXEC dbo.quinzena_item_loja_ii_200907_view
EXEC dbo.EventNotificationErrorsQueue
EXEC dbo.vw_Orcamento
EXEC dbo.XPKC_Venda_MesItemTodoPontoPromCli_PricePoint2
EXEC dbo.sp_diaitemlojai_d_lobras
EXEC dbo.vw_conta_cartao
EXEC dbo.xpkc_saldo_estoque_sap_Wagner
EXEC dbo.regiao_comercial_mms
EXEC dbo.dia_classe_loja_Orcamento
EXEC dbo.PARA_DELETAR_venda_mes_comercialestilopontopromcli_pricepoint_old
EXEC dbo.quinzena_item_loja_i_ptmp_pin
EXEC dbo.dia_comercial_item_loja_ii_200707_view
EXEC dbo.R_9
EXEC dbo.XPKmes_estilo_toda_loja_iii_new
EXEC dbo.dt_verstamp006
EXEC dbo.periodo_item_loja_i_new_old
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200910_view
EXEC dbo.R_336
EXEC dbo.VW_CRED_lc_plastico
EXEC dbo.XPKlk_cd
EXEC dbo.sp_quinzenaitemloja_meses
EXEC DSS.l_setorpp
EXEC dbo.periodo_classe_toda_loja_giro
EXEC dbo.vw_ano_prev_entr
EXEC dbo.sp_reestruturacao_dia_secao_200502_u
EXEC RPCUSER.sp_dias_uteis
EXEC dbo.tb_custo_importados_FULL
EXEC DSS.work_sku_com_custo_errado
EXEC dbo.XPKdia_classe_loja_Orcamento
EXEC dbo.venda_messecaotodopontopromclipagto
EXEC dbo.dia_comercial_item_loja_ii_200708_view
EXEC dbo.lk_cidade_fornecedor
EXEC dbo.dt_getpropertiesbyid_vcs
EXEC dbo.mes_tema_loja_i_new
EXEC dbo.dia_comercial_item_loja_ii_200909_view
EXEC dbo.R_338
EXEC dbo.XPKlk_centro_responsabilidade
EXEC dbo.sp_quinzenaitemloja_temp
EXEC DSS.PK__l_setorPP__6760DD44
EXEC dbo.lk_grupo_centro_responsabilidade
EXEC dbo.lojas_eleitas_venda_orcada2
EXEC dbo.ServiceBrokerQueue
EXEC dbo.vw_cobertura_num_dias_entrega
EXEC dbo.XPKC_Venda_MessecaotodoPontoPromtodoCli_PricePoint2
EXEC dbo.sp_diasecaolojavenda_i
EXEC RPCUSER.57Santin_200902
EXEC dbo.regra_icms
EXEC dbo.alicota_icm_custo_MMS
EXEC dbo.dia_comercial_item_loja_ii_200709_view
EXEC dbo.PK__lk_cidade_fornec__6B25B5D9
EXEC dbo.dt_displayoaerror
EXEC dbo.mes_tema_loja_ii
EXEC dbo.dia_comercial_item_loja_ii_200910_view
EXEC dbo.R_386
EXEC dbo.sp_quinzenaitemlojavenda_i
EXEC dbo.lk_grupo_despesa
EXEC dbo.vw_comprador
EXEC dbo.XPKC_Venda_MesSimilarTodoPontoTodaPromTodoCli_PricePoint
EXEC dbo.sp_diatodoprodlojavenda_i
EXEC dbo.dia_secao_loja_200705_view
EXEC dbo.saldo_inicial_SAP_RT
EXEC dbo.reservatorio_estoque_i
EXEC dbo.alicota_icms_medio_setor_dia
EXEC dbo.dia_comercial_item_loja_i_200811_view
EXEC dbo.dia_comercial_item_loja_ii_200710_view
EXEC dbo.R_1
EXEC dbo.R_5
EXEC dbo.dt_adduserobject_vcs
EXEC dbo.PARA_DELETAR_mes_tema_loja_iii_new
EXEC dbo.dia_comercial_sub_classe_loja_i_200909_view
EXEC dbo.R_422
EXEC dbo.dia_secao_loja_200610_view
EXEC dbo.sp_quinzenaitemtodalojavenda_i
EXEC dbo.lk_grupo_fabricante
EXEC dbo.loja_interligada_plan
EXEC dbo.vw_data_hoje
EXEC dbo.xpkc_saldo_inicial_SAP_RT
EXEC dbo.DF__faixa_tic__id_to__3A193581
EXEC DSS.work_vw_sap_custo_medio_fiscal
EXEC dbo.reservatorio_estoque_ii
EXEC dbo.gera_produtos_mms_teste
EXEC dbo.ano
EXEC dbo.dia_comercial_item_loja_ii_200811_view
EXEC dbo.XPKN_pedido
EXEC dbo.R_10
EXEC dbo.R_104
EXEC dbo.quinzena_item_loja_i_final_luis_view
EXEC dbo.dt_addtosourcecontrol
EXEC dbo.mes_tema_toda_loja_i_new
EXEC dbo.dia_comercial_sub_classe_loja_i_200910_view
EXEC dbo.FK_item_tamanho_tabelaitem
EXEC RPCUSER.sp_atualiza_itemdwh_u
EXEC dbo.XPKlk_cidade_fabricante
EXEC dbo.sp_reestruturacao_dia_secao_200111_u
EXEC dbo.lk_grupo_fornecedor
EXEC dbo.sp_dwh_seleciona_loja_nova_s
EXEC dbo.vw_dia
EXEC dbo.sp_reestruturacao_dia_secao_200503_u
EXEC dbo.sp_estoqueprojetadoorcamento_u
EXEC dbo.dia_secao_loja_i_comercial_ptmp
EXEC dbo.dia_item_loja_i_200903_new
EXEC dbo.DF__ITEM__ID_TIPO_IT__637050CF
EXEC dbo.dia_sub_classe_loja_i_comercial_ptmp
EXEC dbo.saida_cd
EXEC dbo.dia_comercial_sub_classe_loja_i_200811_view
EXEC dbo.R_13
EXEC dbo.R_105
EXEC dbo.dt_checkinobject
EXEC dbo.quinzena_item_loja_i_final_new_stg
EXEC dbo.periodo_item_loja_i_200909_view
EXEC dbo.FK_tipo_item_tamanho_tabelaitem
EXEC dbo.sp_reestruturacao_dia_secao_200112_u
EXEC dbo.lk_grupo_loja_mms
EXEC dbo.vw_dia_anterior
EXEC dbo.cad_clientes
EXEC dbo.sp_dw_CargaPedidos_Agrega_i
EXEC dbo.quinzena_item_loja_200903_view
EXEC dbo.DF__ITEM__ID_ITEM_TA__64647508
EXEC dbo.sp_sap_i_fi_gl_12_s
EXEC dbo.dia_sub_classe_loja_i_final_new
EXEC dbo.saida_cd_detal
EXEC dbo.banco
EXEC dbo.periodo_item_loja_i_200811_view
EXEC dbo.R_alt_2
EXEC dbo.xpkc_MargemNegativaSAPtxt
EXEC dbo.dt_checkoutobject
EXEC dbo.quinzena_item_loja_ii_final_stg
EXEC dbo.mes_tema_toda_loja_ii
EXEC dbo.periodo_item_loja_i_200910_view
EXEC dbo.R_147
EXEC DSS.PARA_DELETAR_bkp_dia_loja_venda_extranet2
EXEC dbo.XPKlk_cidade_local
EXEC dbo.sp_reestruturacao_dia_secao_200201_u
EXEC dbo.lk_grupo_receita
EXEC dbo.vw_dia_associacao
EXEC dbo.xpkc_alicota_icms_medio_setor_dia
EXEC dbo.sp_reestruturacao_dia_secao_200504_u
EXEC dbo.sp_dw_CargaPedidos_i
EXEC dbo.quinzena_item_loja_ii_200903_view
EXEC dbo.DF__item__id_tema__2D55CDEE
EXEC DSS.PARA_DELETAR_sdk_previsao_custo
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200811_view
EXEC DSS.periodo_sub_classe_loja_i_200910_view
EXEC dbo.R_107
EXEC dbo.cmpSAP_full
EXEC dbo.dt_isundersourcecontrol
EXEC dbo.PARA_DELETAR_mes_tema_toda_loja_iii_new
EXEC dbo.dia_item_loja_sap_carga_FastLoad
EXEC dbo.R_148
EXEC DSS.DECOM_estilos_liquidacao_verao_sul_2008_compras
EXEC dbo.XPKlk_cidade_loja
EXEC dbo.sp_reestruturacao_dia_secao_200202_u
EXEC dbo.lk_grupo_tributario
EXEC dbo.vw_dia_calendario_comercial
EXEC dbo.dia_comercial_item_loja_i_200802_view
EXEC dbo.XPKano
EXEC dbo.sp_dw_cd_fornecedor
EXEC dbo.dia_secao_loja_i_ptmp
EXEC dbo.dia_secao_loja_200903_view
EXEC dbo.dia_sub_classe_loja_ii
EXEC dbo.semana_comercial_item_loja_i_200811_view
EXEC dbo.dia_item_loja_i_200712_new
EXEC dbo.lk_cidade_dev
EXEC dbo.R_108
EXEC dbo.xpkc_cmp_sap_full
EXEC dbo.PK_mes_plfam_loja_tdforn_origem
EXEC dbo.dt_removefromsourcecontrol
EXEC dbo.R_334
EXEC DSS.lk_padrinho_loja
EXEC dbo.XPKlk_cidade_transp
EXEC dbo.sp_reestruturacao_dia_secao_200203_u
EXEC dbo.lk_hora
EXEC dbo.vw_dia_entrega_sol
EXEC dbo.dia_comercial_item_loja_ii_200802_view
EXEC dbo.xak_banco
EXEC dbo.sp_reestruturacao_dia_secao_200505_u
EXEC dbo.sp_dw_cd_work_u
EXEC dbo.pedidos_erro
EXEC dbo.dia_secao_loja_ii
EXEC dbo.dia_comercial_item_loja_i_200901_view
EXEC dbo.DF__lk_client__id_fa__052715AC
EXEC dbo.dia_sub_classe_toda_loja_i_new
EXEC DSS.PARA_DELETAR_sdk_venda_orcada_loja_ano
EXEC dbo.dia_secao_loja_200702_view
EXEC RPCUSER.calendario_tst
EXEC dbo.dia_item_loja_i_200901_new
EXEC dbo.lk_estado_dev
EXEC dbo.R_110
EXEC dbo.cmpsap_numeric
EXEC dbo.dt_validateloginparams
EXEC dbo.moeda
EXEC dbo.dia_sub_classe_loja_200807_view
EXEC dbo.XPKlk_classe
EXEC dbo.dia_secao_loja_200601_view
EXEC dbo.sp_reestruturacao_dia_secao_200204_u
EXEC dbo.lk_instrucao_cliente
EXEC dbo.vw_dia_inventario
EXEC dbo.dia_comercial_sub_classe_loja_i_200802_view
EXEC RPCUSER.xpkc_calendario_tst
EXEC dbo.sp_dw_loja_s
EXEC dbo.log_pedidos_estoque
EXEC dbo.dia_secao_loja_iii_new
EXEC dbo.dia_comercial_item_loja_ii_200901_view
EXEC dbo.DF__lk_client__id_to__0C691018
EXEC dbo.dia_sub_classe_toda_loja_ii
EXEC dbo.secao
EXEC dbo.carga_dwh_processos_adicionais
EXEC dbo.dia_secao_loja_200901_view
EXEC dbo.dia_secao_loja_200709_view
EXEC dbo.R_85
EXEC dbo.xpkc_cmpsap_numeric
EXEC dbo.PK_mes_plfam_tdloja_tdforn_origem
EXEC dbo.dt_vcsenabled
EXEC dbo.motivo_remarca
EXEC dbo.periodo_sub_classe_loja_i_ptmp
EXEC RPCUSER.sp_dw_cd_work_u
EXEC dbo.XPKlk_classe_despesa
EXEC dbo.sp_reestruturacao_dia_secao_200205_u
EXEC dbo.sp_carga_setorespp
EXEC dbo.lk_item
EXEC dbo.sp_dwh_loja_interligada_i
EXEC dbo.vw_dia_pl_setor_loja_Orcamento
EXEC dbo.periodo_item_loja_i_200802_view
EXEC dbo.xpkc_carga_dwh_processos_adicionais
EXEC dbo.sp_reestruturacao_dia_secao_i_final_u
EXEC dbo.sp_dw_pl_familia_s
EXEC dbo.pk_log_pedidos_estoque
EXEC dbo.dia_comercial_sub_classe_loja_i_200901_view
EXEC dbo.dia_todo_item_loja_i_new
EXEC dbo.secao_loja_corrente
EXEC dbo.quinzena_item_loja_200901_view
EXEC dbo.sp_dwh_planejamento_venda_semana_comercial_s
EXEC dbo.R_89
EXEC DSS.quinzena_item_todaloja_i_new_TSTSAP_vw
EXEC dbo.XPKmes_secao_toda_loja_i
EXEC dbo.dt_whocheckedout
EXEC dbo.movto_solicitacao
EXEC DSS.periodo_sub_classe_loja_i_ptmp
EXEC dbo.XPKlk_classe_receita
EXEC dbo.sp_reestruturacao_dia_secao_200206_u
EXEC dbo.sp_carga_usuariospp
EXEC dbo.lk_item_tamanho
EXEC dbo.dia_comercial_item_loja_i_200606_view
EXEC dbo.vw_dia_prev_entr
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200802_view
EXEC dbo.sp_DW_PrecoUnitario_u
EXEC dbo.sp_pedidos_i
EXEC dbo.dia_secao_toda_loja_i_new
EXEC dbo.periodo_item_loja_i_200901_view
EXEC dbo.dia_todo_item_loja_ii
EXEC dbo.carga_estoque_loja_xml_mms
EXEC dbo.quinzena_item_loja_ii_200901_view
EXEC dbo.semana_comercial_item_loja_i_200707_view
EXEC dbo.R_220
EXEC dbo.cmpSAP_full_BKP
EXEC dbo.XPKmes_secao_toda_loja_2
EXEC dbo.dt_addtosourcecontrol_u
EXEC DSS.mudanca_negocio
EXEC DSS.periodo_sub_classe_loja_i_new_teste
EXEC DSS.DECOM_liquida_verao_2009
EXEC dbo.sp_reestruturacao_dia_secao_200207_u
EXEC dbo.sp_carga_faixa_horapp
EXEC dbo.lk_local
EXEC dbo.dia_comercial_sub_classe_loja_i_200606_view
EXEC dbo.vw_dia_ult_pos_estoque
EXEC dbo.semana_comercial_item_loja_i_200802_view
EXEC dbo.xpkc_carga_estoque_loja_xml_mms
EXEC dbo.sp_dw_regiao_comercial_s
EXEC dbo.sp_pedidos_u
EXEC dbo.dia_secao_toda_loja_ii
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200901_view
EXEC dbo.sp_SAP_I_CO_01_d
EXEC dbo.dia_todo_item_toda_loja_i_new
EXEC dbo.carga_loja
EXEC dbo.semana_comercial_item_loja_i_200708_view
EXEC dbo.R_alt_39
EXEC dbo.cmp_sap_Escribano_Maximo
EXEC dbo.XPKmes_secao_toda_loja_iii
EXEC dbo.dt_checkinobject_u
EXEC DSS.periodo_sub_classe_loja_i_200908_view
EXEC DSS.DECOM_liquida_verao_sul_01_06
EXEC dbo.XPKlk_cliente
EXEC dbo.sp_reestruturacao_dia_secao_200208_u
EXEC dbo.lk_loja
EXEC dbo.periodo_item_loja_i_200606_view
EXEC dbo.vw_dias_cobertura_estoques
EXEC dbo.proc_filtro_clientes_cad
EXEC dbo.sp_dw_regiao_geografica_s
EXEC dbo.sp_pedidos_erro_s
EXEC dbo.dia_semana
EXEC dbo.semana_comercial_item_loja_i_200901_view
EXEC dbo.faixa_tic__id_to__3A193581
EXEC dbo.dia_todo_item_toda_loja_ii
EXEC dbo.carga_venda_prom
EXEC DSS.dia_secao_loja_sap_vw
EXEC dbo.semana_comercial_item_loja_i_200709_view
EXEC dbo.R_alt_40
EXEC dbo.dt_checkoutobject_u
EXEC DSS.periodo_sub_classe_loja_i_200909_view
EXEC dbo.XPKcomprador
EXEC dbo.sp_reestruturacao_dia_secao_200209_u
EXEC dbo.lk_loja_faixa_preco
EXEC RPCUSER.string_siv
EXEC dbo.vw_dias_estoq_hoje
EXEC dbo.PK__cobertura_ideal___73F00604
EXEC dbo.sp_dw_SIG_Grupo_Links_u
EXEC dbo.sp_dw_CargaPedidos_MMS_i_bkp
EXEC dbo.dia_semana_anterior
EXEC dbo.DF__dia__id_semestre__7DCF41507
EXEC dbo.dia_todo_prod_loja_i
EXEC dbo.semana_comercial_estilo_loja_ii
EXEC dbo.vw_quinzena_item_loja_i_final_contabil
EXEC dbo.vw_dia_item_loja_dwh_merge
EXEC dbo.Planejamento_semana_comercial_dw_empresa
EXEC dbo.dia_comercial_sub_classe_loja_i_200710_view
EXEC dbo.R_alt_41
EXEC dbo.cmpSAP_full_MAXIMO
EXEC dbo.dt_displayoaerror_u
EXEC DSS.periodo_sub_classe_loja_i_200907_view
EXEC dbo.XPKlk_depto
EXEC dbo.sp_reestruturacao_dia_secao_200210_u
EXEC dbo.lk_lote_cd
EXEC dbo.vw_dias_uteis
EXEC dbo.dia_item_loja_i_200804_new
EXEC dbo.sp_dw_SIG_Grupo_u
EXEC dbo.sp_estoq_LogPedidos_s
EXEC dbo.dia_sub_depto_loja_orcamento
EXEC dbo.tbTempMov_Z57_Z58
EXEC dbo.DFITEMIDIPOT
EXEC dbo.dia_todo_prod_toda_loja_i
EXEC dbo.semana_comercial_estilo_toda_loja_i_new
EXEC DSS.vw_semana_comercial_item_loja_sap
EXEC DSS.sp_dwh_planejamento_venda_semana_comercial_s
EXEC dbo.periodo_item_loja_i_200710_view
EXEC dbo.R_alt_43
EXEC dbo.lk_tema
EXEC dbo.xak1_cmpSAP_full_MAXIMO
EXEC dbo.dt_getpropertiesbyid_vcs_u
EXEC dbo.negocio
EXEC DSS.periodo_sub_classe_loja_i_200906_view
EXEC dbo.dia_item_loja_i_200808_new
EXEC dbo.XPK_lk_despesa
EXEC dbo.sp_reestruturacao_dia_secao_200211_u
EXEC dbo.lk_manifesto_carga
EXEC dbo.dia_secao_loja_200608_view
EXEC dbo.vw_dias_uteis_dta_ult_entr_merc
EXEC dbo.quinzena_item_loja_200804_view
EXEC dbo.xpkcotacao_moeda
EXEC dbo.sp_dw_SIG_Grupo_Usuario_u
EXEC dbo.sp_estoq_LogPedidos_d
EXEC dbo.dia_sub_depto_loja_est
EXEC dbo.DF_tbTempMov_Z57_Z58_DTENTRADA
EXEC dbo.DFsupervisositua
EXEC dbo.twork_sap_receita_deducao_venda
EXEC dbo.lk_faixa_ticket_numerica
EXEC dbo.semana_comercial_estilo_toda_loja_ii
EXEC DSS.vw_dia_secao_loja_sap
EXEC dbo.semana_comercial_item_loja_i_200710_view
EXEC dbo.R_51
EXEC dbo.lk_todo_Tema
EXEC dbo.XPKmes_sub_classe_estado_i_new
EXEC dbo.dt_isundersourcecontrol_u
EXEC DSS.periodo_sub_classe_loja_i_200905_view
EXEC DSS.ncs_event_troco
EXEC dbo.tmp_venda_ods
EXEC dbo.dia_secao_loja_200808_view
EXEC dbo.sp_reestruturacao_dia_secao_200212_u
EXEC dbo.lk_meio_pagto
EXEC dbo.vw_dias_uteis_prox_75dias
EXEC dbo.quinzena_item_loja_ii_200804_view
EXEC dbo.sp_dw_SIG_Links_s
EXEC dbo.sp_carga_pedido_MMS_d
EXEC dbo.DF_tbTempMov_Z57_Z58_FLENVIO
EXEC dbo.margem_estoque
EXEC dbo.venda_unitaria_item_loja
EXEC dbo.cobertura_ideal_setor_lead_time
EXEC DSS.vw_dia_todo_prod_loja_sap
EXEC dbo.loja
EXEC dbo.semana_comercial_item_loja_ii_ptmp
EXEC dbo.R_52
EXEC dbo.loja_setor_price_point
EXEC dbo.custo_SAP_Agosto
EXEC dbo.XPKmes_sub_classe_estado_ii
EXEC dbo.dt_validateloginparams_u
EXEC dbo.orcamento
EXEC DSS.periodo_sub_classe_loja_i_200904_view
EXEC dbo.dia_item_loja_cancelamento
EXEC dbo.sp_atualiza_posicao_mms_u
EXEC dbo.quinzena_item_loja_200808_view
EXEC dbo.sp_reestruturacao_dia_secao_200301_u
EXEC dbo.vw_feriado_lojaf
EXEC dbo.sp_dw_SIG_Links_u
EXEC dbo.dia_comercial_item_loja_i_200703_view
EXEC dbo.dia_sub_depto_toda_loja_est
EXEC DSS.work_sap_receita_deducao_venda
EXEC dbo.mes_secao_toda_loja_i
EXEC dbo.XPKvenda_unitaria_item_loja_MIGRACAO
EXEC DSS.vw_mes_item_loja_sap
EXEC dbo.DF__loja__cd_origem___36297463
EXEC dbo.semana_comercial_item_loja_ii
EXEC dbo.R_53
EXEC DSS.quinzena_item_loja_i_final_new_TSTSAP_vw
EXEC dbo.XPKmes_sub_classe_estado_iii_new
EXEC dbo.dt_whocheckedout_u
EXEC dbo.origem_item
EXEC dbo.loja_fechada_antiga
EXEC DSS.periodo_sub_classe_loja_i_200903_view
EXEC dbo.xpkc_dia_item_loja_cancelamento
EXEC RPCUSER.tmp_venda
EXEC dbo.quinzena_item_loja_ii_200808_view
EXEC dbo.sp_reestruturacao_dia_secao_200302_u
EXEC dbo.lk_negocio_loja
EXEC dbo.sdk_venda_orcada_loja_ano
EXEC dbo.vw_fornecedor
EXEC dbo.sp_dw_SIG_Usuario_Links_u
EXEC dbo.dia_comercial_item_loja_ii_200703_view
EXEC dbo.spBTS_Mov_Z57_Z58
EXEC DSS.work_vw_sap_receita_deducao_envio
EXEC dbo.mes_sub_classe_loja_forn_ped
EXEC dbo.semana_comercial_sub_classe_loja_i_new
EXEC dbo.cotacao_moeda
EXEC dbo.dia_item_loja_sap
EXEC dbo.DF__loja__id_regiao___159E3FEE
EXEC DSS.sp_cria_estoque_auditoria_s
EXEC dbo.R_54
EXEC dbo.spBTSInsereCuponsFaixa_ATM_DWH
EXEC dbo.origem_pedido
EXEC dbo.XPKloja_fechada_antiga
EXEC DSS.periodo_sub_classe_loja_i_200902_view
EXEC dbo.lk_fornecedor_base
EXEC dbo.MargemNegativaSAP_OLD
EXEC dbo.XPKlk_dia
EXEC dbo.sp_reestruturacao_dia_secao_200303_u
EXEC dbo.eventos_mms_regulares
EXEC dbo.vw_grupo_inter_com
EXEC dbo.PK__custo_unitario_i__79A8DF5A
EXEC dbo.sp_dw_SIG_Usuario_u
EXEC dbo.dia_comercial_sub_classe_loja_i_200703_view
EXEC dbo.sp_work_marisa_new_MMS
EXEC dbo.mes_sub_classe_loja_tdforn_origem
EXEC dbo.semana_comercial_sub_classe_loja_ii
EXEC dbo.DF__loja__id_distrit__25D4A7B7
EXEC dbo.R_66
EXEC dbo.periodo_item_loja_i_200707_view
EXEC dbo.pedido
EXEC dbo.DF__loja_fechada_antiga__cd_origem___36297463
EXEC DSS.periodo_sub_classe_loja_i_200901_view
EXEC dbo.XPKlk_fornecedor_base
EXEC dbo.xpkc_lk_empresa_custodia
EXEC dbo.sp_reestruturacao_dia_secao_200304_u
EXEC dbo.lk_ocupacao_cliente
EXEC dbo.xpkc_EVENTOS_MMS_REGULARES
EXEC dbo.vw_grupo_inter_com_x
EXEC dbo.xpkc_custo_unitario_medio_item_mms2
EXEC dbo.sp_dw_supervisor_regional_s
EXEC dbo.periodo_item_loja_i_200703_view
EXEC dbo.dia_toda_loja_todo_prod_cancelamento_venda_siv
EXEC dbo.tbMov_Z57_Z58
EXEC dbo.mes_sub_classe_tdloja_forn_ped
EXEC dbo.semana_comercial_sub_classe_toda_loja_i_new
EXEC dbo.DF__loja__id_toda_re__29A5389B
EXEC dbo.dia_comercial_item_loja_i_200711_view
EXEC dbo.R_67
EXEC dbo.XPKmes_sub_classe_loja_iii_new
EXEC dbo.dia_comercial_sub_classe_loja_i_200707_view
EXEC dbo.DF__loja_fechada_antiga__id_regiao___159E3FEE
EXEC DSS.periodo_sub_classe_loja_i_LESS_200901_view
EXEC dbo.R_alt_3
EXEC dbo.dia_comercial_item_loja_i_200806_view
EXEC dbo.XPKlk_estacao
EXEC dbo.sp_reestruturacao_dia_secao_200305_u
EXEC dbo.lk_origem_cadastro_cliente
EXEC DSS.DECOM_liquida_banana_verao_julho_2009
EXEC dbo.vw_item_loja_corrente
EXEC DSS.up_prev_vda_atualiza_indicador
EXEC dbo.PK__dia__4990833B
EXEC dbo.sp_DWCarga_CustoVenda_i
EXEC dbo.dia_toda_loja_venda_extranet2
EXEC dbo.item2_BKP_20090313
EXEC dbo.DF__mes__id_semestre__79FEB06C
EXEC dbo.mes_sub_classe_tdloja_tdforn_origem
EXEC dbo.semana_comercial_sub_classe_toda_loja_ii
EXEC dbo.DF__loja__id_grupo_l__03C0522C
EXEC dbo.dia_comercial_item_loja_ii_200711_view
EXEC dbo.R_69
EXEC dbo.XPKmes_sub_depto_loja_Orcamento
EXEC dbo.sp_work_estoque_reservado_i
EXEC dbo.periodo_anterior_calendario_comercial
EXEC dbo.DF__loja_fechada_antiga__id_distrit__25D4A7B7
EXEC dbo.FK_tipo_item_tamanho
EXEC dbo.R_alt_6
EXEC dbo.dia_comercial_item_loja_ii_200806_view
EXEC dbo.sp_reestruturacao_dia_secao_200306_u
EXEC dbo.lk_plano
EXEC DSS.DECOM_liquida_banana_verao_julho_2009_VII
EXEC dbo.vw_itens_promocao_01
EXEC dbo.dia_secao_loja_200710_view
EXEC dbo.PK__dia_ano_anterior__7C854C05
EXEC DSS.sp_dwh_acumulado_ano_s
EXEC dbo.dia_todo_prod_loja_i_new
EXEC dbo.dia_comercial_item_loja_i_200604_view
EXEC dbo.mes_sub_classe_toda_loja_i
EXEC dbo.semana_mes
EXEC dbo.XPKloja
EXEC dbo.dia_comercial_sub_classe_loja_i_200711_view
EXEC dbo.R_alt_68
EXEC dbo.xpkc_mes_sub_depto_loja_est2
EXEC dbo.VER_IO
EXEC dbo.sp_work_marisa_Estoque_Reservado_t
EXEC dbo.sp_carga_orcamento_calendario_comercial_pege_dw_i
EXEC dbo.periodo_calendario_comercial
EXEC dbo.DF__loja_fechada_antiga__id_toda_re__29A5389B
EXEC dbo.dia_secao_loja_i_final_new
EXEC dbo.R_81
EXEC dbo.carga_dwh_financ
EXEC dbo.dia_comercial_sub_classe_loja_i_200806_view
EXEC dbo.XPKlk_estado_cd
EXEC dbo.sp_reestruturacao_dia_secao_200307_u
EXEC dbo.lk_ponto_venda
EXEC DSS.DECOM_liquida_banana_verao_2009_II
EXEC dbo.venda_planejada_periodo_comercial_empresa
EXEC dbo.vw_itens_promocao_02
EXEC dbo.dia_sub_classe_loja_200710_view
EXEC dbo.PKC_dia_calendario_comercial
EXEC dbo.sp_dwh_anexo3_int_s
EXEC dbo.dia_todo_prod_loja_ii
EXEC dbo.sp_carrega_tbl_particionada_comercial_i
EXEC dbo.dia_secao_toda_loja_sap
EXEC dbo.periodo_item_loja_i_200604_view
EXEC dbo.mes_sub_classe_toda_loja_i_new
EXEC dbo.semana_sub_classe_loja_forn_ped
EXEC dbo.xfk_loja_x_lk_loja_faixa_preco
EXEC dbo.periodo_item_loja_i_200711_view
EXEC dbo.CMP_SAP_Carga
EXEC dbo.sp_work_marisa_MMS_new_fixa
EXEC dbo.DF__loja_fechada_antiga__id_grupo_l__03C0522C
EXEC dbo.R_alt_81
EXEC dbo.periodo_item_loja_i_200806_view
EXEC dbo.PK__lk_estado_civil__2588F846
EXEC dbo.sp_reestruturacao_dia_secao_200308_u
EXEC DSS.f_rodes_item_dia_hora_loja
EXEC dbo.lk_promocao
EXEC dbo.PK__venda_planejada___13897845
EXEC dbo.vw_last3meses
EXEC dbo.dia_secao_loja_200711_view
EXEC dbo.PK__dia_calendario_c__7E6D9477
EXEC DSS.sp_dwh_CarregaVendas_s
EXEC dbo.sp_carga_pedido_MMS_i
EXEC dbo.dia_todo_prod_loja_iii_new
EXEC DSS.vw_dia_secao_toda_loja_sap
EXEC dbo.DF__periodo_c__id_si__364BD1F9
EXEC dbo.dia_comercial_sub_classe_loja_i_200604_view
EXEC dbo.mes_sub_classe_toda_loja_ii
EXEC dbo.semestre
EXEC dbo.custo_unitario_item_loja_medio_CD
EXEC dbo.xfkc_id_distrito_comercial_mms
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200711_view
EXEC dbo.vw_mv_quinzena_item_negocio_i_new
EXEC dbo.periodo_estilo_loja_i_new
EXEC dbo.xfk_loja_fechada_antiga_x_lk_loja_faixa_preco
EXEC dbo.semana_comercial_item_loja_i_new
EXEC dbo.xfk_lk_banco_empresa_custodia_lk_banco
EXEC dbo.SEMANA_COMERCIAL_ESTILO_LOJA_200806_view
EXEC dbo.XPKlk_estado_fabricante
EXEC dbo.sp_reestruturacao_dia_secao_200309_u
EXEC dbo.lk_quinzena
EXEC dbo.calendario_tst
EXEC DSS.sp_atualiza_venda_prevista_setor_u_2
EXEC dbo.vw_last3mesesposestoque
EXEC dbo.dia_sub_classe_loja_200711_view
EXEC dbo.XPKdia_comercial_sub_depto_loja_orcamento
EXEC dbo.sp_dwh_centro_responsabilidade_s
EXEC dbo.sp_dw_CargaPedidos_Agrega_MMS_i
EXEC DSS.DECOM_estoque_anterior_14_12_2008
EXEC dbo.parametro_dw
EXEC dbo.dia_item_loja_i_final_new_CTB
EXEC dbo.custo_unitario_medio_item_mms
EXEC dbo.xfkc_id_regiao_comercial_mms
EXEC dbo.semana_comercial_item_loja_i_200711_view
EXEC dbo.CMP_SAP_historico
EXEC dbo.sp_work_marisa_MMS_t_fixa
EXEC dbo.vw_mes_loja_profissao_qtde_contas
