ALTER DATABASE RH_PRD_DESENV
MODIFY FILE
--(NAME = RH_PRD_Data, FILENAME = N'E:\MSSQL\Data\RH_PRD_DESENV\RH_DESENV_01.mdf')
--(NAME = RH_PRD_Data_02, FILENAME = N'E:\MSSQL\Data\RH_PRD_DESENV\RH_DESENV_02.mdf')
--(NAME = RH_PRD_Data_03, FILENAME = N'E:\MSSQL\Data\RH_PRD_DESENV\RH_DESENV_03.mdf')
(NAME = RH_PRD_Data_04, FILENAME = N'E:\MSSQL\Data\RH_PRD_DESENV\RH_DESENV_04.ndf')
--(NAME = RH_PRD_Data_05, FILENAME = N'E:\MSSQL\Data\RH_PRD_DESENV\RH_DESENV_05.ndf')
--(NAME = RH_PRD_Data_06, FILENAME = N'E:\MSSQL\Data\RH_PRD_DESENV\RH_DESENV_06.ndf')
(NAME = RH_PRD_Log, FILENAME = N'D:\LOGS\RH_PRD_DESENV\RH_PRD_DESENV_log.ldf')


ALTER DATABASE 



ALTER DATABASE DW_PRD_MARISA
MODIFY FILE 
--(NAME = DW_PRD_MARISA_DATA_27, FILENAME = 'Q:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_DATA_27.ndf')
--(NAME = DW_PRD_MARISA_28, FILENAME = 'S:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_28.ndf')
(NAME = DW_PRD_MARISA_DATA_2_31, FILENAME = 'S:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_DATA_2_31.ndf')

select * from sysaltfiles

update sysaltfiles set filename = 'Q:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_DATA_27.ndf'
where filename = 'O:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_DATA_27.ndf'

O:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_DATA_27.ndf
O:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_28.ndf
Q:\DW_PRD_MARISA\DATA\DW_PRD_MARISA_DATA_2_31.ndf
